/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { CustomMapData } from '../types';

export const PREMADE_MAPS: CustomMapData[] = [
  {
    id: 'cyber_hex_arena',
    name: 'Cyber Hex Grid',
    description: 'A sci-fi tactical holodeck featuring glowing neon pillars and a central energy core. Great for fast-paced skirmishes.',
    author: 'System Presets',
    theme: 'cyberpunk',
    arenaRadius: 20,
    skyboxHue: 280, // Magenta/purple twilight
    skyboxBrightness: 5,
    fogColor: '#0c0714',
    fogDensity: 0.02,
    spawnPoints: [
      { x: -12, y: 0, z: -12 },
      { x: 12, y: 0, z: 12 },
      { x: -12, y: 0, z: 12 },
      { x: 12, y: 0, z: -12 },
      { x: 0, y: 0, z: -14 },
      { x: 0, y: 0, z: 14 },
      { x: -14, y: 0, z: 0 },
      { x: 14, y: 0, z: 0 }
    ],
    lighting: {
      ambientColor: '#0f0c1b',
      ambientIntensity: 0.7,
      directColor: '#e0f2fe',
      directIntensity: 1.8,
      directPosition: { x: 5, y: 15, z: 5 },
      pointLights: [
        { id: 'core_glow', color: '#a855f7', intensity: 4.5, distance: 20, decay: 1.5, position: { x: 0, y: 3.5, z: 0 } },
        { id: 'left_vent', color: '#06b6d4', intensity: 2.5, distance: 10, decay: 1.2, position: { x: -8, y: 2, z: 0 } },
        { id: 'right_vent', color: '#06b6d4', intensity: 2.5, distance: 10, decay: 1.2, position: { x: 8, y: 2, z: 0 } }
      ]
    },
    objects: [
      // Central glowing energy core
      {
        id: 'obj_central_core',
        name: 'Plasma Core Reactor',
        type: 'sphere',
        position: { x: 0, y: 1.5, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 3.5, y: 3.5, z: 3.5 }, // Diameter
        color: '#a855f7',
        metalness: 0.2,
        roughness: 0.1,
        opacity: 0.95,
        transparent: true,
        emissive: '#7e22ce',
        emissiveIntensity: 3.0,
        isCollidable: true,
        texture: 'futuristic_shield'
      },
      // Corner carbon fiber pillars
      {
        id: 'obj_pillar_nw',
        name: 'Hex Tech Column NW',
        type: 'cylinder',
        position: { x: -8, y: 3, z: -8 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.8, y: 6, z: 1.8 }, // scale.x is diameter
        color: '#1e293b',
        metalness: 0.9,
        roughness: 0.15,
        opacity: 1,
        transparent: false,
        emissive: '#06b6d4',
        emissiveIntensity: 1.2,
        isCollidable: true,
        texture: 'futuristic_hex'
      },
      {
        id: 'obj_pillar_ne',
        name: 'Hex Tech Column NE',
        type: 'cylinder',
        position: { x: 8, y: 3, z: -8 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.8, y: 6, z: 1.8 },
        color: '#1e293b',
        metalness: 0.9,
        roughness: 0.15,
        opacity: 1,
        transparent: false,
        emissive: '#06b6d4',
        emissiveIntensity: 1.2,
        isCollidable: true,
        texture: 'futuristic_hex'
      },
      {
        id: 'obj_pillar_se',
        name: 'Hex Tech Column SE',
        type: 'cylinder',
        position: { x: 8, y: 3, z: 8 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.8, y: 6, z: 1.8 },
        color: '#1e293b',
        metalness: 0.9,
        roughness: 0.15,
        opacity: 1,
        transparent: false,
        emissive: '#06b6d4',
        emissiveIntensity: 1.2,
        isCollidable: true,
        texture: 'futuristic_hex'
      },
      {
        id: 'obj_pillar_sw',
        name: 'Hex Tech Column SW',
        type: 'cylinder',
        position: { x: -8, y: 3, z: 8 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.8, y: 6, z: 1.8 },
        color: '#1e293b',
        metalness: 0.9,
        roughness: 0.15,
        opacity: 1,
        transparent: false,
        emissive: '#06b6d4',
        emissiveIntensity: 1.2,
        isCollidable: true,
        texture: 'futuristic_hex'
      },
      // Carbon fiber defensive partitions
      {
        id: 'obj_barrier_north',
        name: 'Tactical Shield Block N',
        type: 'box',
        position: { x: 0, y: 1.25, z: -7 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 4, y: 2.5, z: 0.8 },
        color: '#0f172a',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0,
        isCollidable: true,
        texture: 'futuristic_carbon'
      },
      {
        id: 'obj_barrier_south',
        name: 'Tactical Shield Block S',
        type: 'box',
        position: { x: 0, y: 1.25, z: 7 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 4, y: 2.5, z: 0.8 },
        color: '#0f172a',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0,
        isCollidable: true,
        texture: 'futuristic_carbon'
      },
      // Low crates you can jump on top of
      {
        id: 'obj_crate_w',
        name: 'Recharge Substation W',
        type: 'box',
        position: { x: -6, y: 0.8, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.6, y: 1.6, z: 1.6 },
        color: '#1e293b',
        metalness: 0.7,
        roughness: 0.3,
        opacity: 1,
        transparent: false,
        emissive: '#ec4899',
        emissiveIntensity: 0.8,
        isCollidable: true,
        texture: 'futuristic_carbon'
      },
      {
        id: 'obj_crate_e',
        name: 'Recharge Substation E',
        type: 'box',
        position: { x: 6, y: 0.8, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.6, y: 1.6, z: 1.6 },
        color: '#1e293b',
        metalness: 0.7,
        roughness: 0.3,
        opacity: 1,
        transparent: false,
        emissive: '#ec4899',
        emissiveIntensity: 0.8,
        isCollidable: true,
        texture: 'futuristic_carbon'
      }
    ]
  },
  {
    id: 'botanical_outpost',
    name: 'Jungle Ruined Outpost',
    description: 'A crumbling modular training center overtaken by nature. Features stone boulders, wooden structures, and mossy cover.',
    author: 'System Presets',
    theme: 'nature',
    arenaRadius: 21,
    skyboxHue: 120, // Greenish atmospheric light
    skyboxBrightness: 6,
    fogColor: '#051208',
    fogDensity: 0.03,
    spawnPoints: [
      { x: -14, y: 0, z: -8 },
      { x: 14, y: 0, z: 8 },
      { x: -8, y: 0, z: 14 },
      { x: 8, y: 0, z: -14 },
      { x: -15, y: 0, z: 0 },
      { x: 15, y: 0, z: 0 },
      { x: 0, y: 0, z: -15 },
      { x: 0, y: 0, z: 15 }
    ],
    lighting: {
      ambientColor: '#0a1d0f',
      ambientIntensity: 0.8,
      directColor: '#fef08a', // Sunlight filtering through canopy
      directIntensity: 2.0,
      directPosition: { x: -6, y: 18, z: -4 },
      pointLights: [
        { id: 'crystal_1', color: '#10b981', intensity: 3.0, distance: 12, decay: 1.1, position: { x: 0, y: 2, z: 0 } },
        { id: 'crystal_2', color: '#eab308', intensity: 2.0, distance: 8, decay: 1.0, position: { x: -9, y: 1.5, z: -9 } },
        { id: 'crystal_3', color: '#eab308', intensity: 2.0, distance: 8, decay: 1.0, position: { x: 9, y: 1.5, z: 9 } }
      ]
    },
    objects: [
      // Central Mystical Totem Crystal
      {
        id: 'obj_nature_totem',
        name: 'Ancient emerald crystal',
        type: 'cylinder',
        position: { x: 0, y: 2, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 4, z: 1.2 },
        color: '#10b981',
        metalness: 0.1,
        roughness: 0.05,
        opacity: 0.85,
        transparent: true,
        emissive: '#047857',
        emissiveIntensity: 2.5,
        isCollidable: true,
        texture: 'fantasy_runed_stone'
      },
      // Giant natural mossy boulders
      {
        id: 'obj_rock_nw',
        name: 'Mossy Boulder NW',
        type: 'box',
        position: { x: -9, y: 1.5, z: -9 },
        rotation: { x: 0, y: 0.3, z: 0 },
        scale: { x: 3, y: 3, z: 3 },
        color: '#2d3748',
        metalness: 0.1,
        roughness: 0.9,
        opacity: 1,
        transparent: false,
        emissive: '#166534',
        emissiveIntensity: 0.3, // faint moss glow
        isCollidable: true,
        texture: 'nature_mossy_stone'
      },
      {
        id: 'obj_rock_se',
        name: 'Mossy Boulder SE',
        type: 'box',
        position: { x: 9, y: 1.5, z: 9 },
        rotation: { x: 0, y: -0.2, z: 0 },
        scale: { x: 3, y: 3, z: 3 },
        color: '#2d3748',
        metalness: 0.1,
        roughness: 0.9,
        opacity: 1,
        transparent: false,
        emissive: '#166534',
        emissiveIntensity: 0.3,
        isCollidable: true,
        texture: 'nature_mossy_stone'
      },
      // Massive Tree Trunks
      {
        id: 'obj_trunk_ne',
        name: 'Forest Giant NE',
        type: 'cylinder',
        position: { x: 9, y: 3.5, z: -9 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 2, y: 7, z: 2 },
        color: '#451a03',
        metalness: 0.05,
        roughness: 0.95,
        opacity: 1,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0,
        isCollidable: true,
        texture: 'nature_wood'
      },
      {
        id: 'obj_trunk_sw',
        name: 'Forest Giant SW',
        type: 'cylinder',
        position: { x: -9, y: 3.5, z: 9 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 2, y: 7, z: 2 },
        color: '#451a03',
        metalness: 0.05,
        roughness: 0.95,
        opacity: 1,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0,
        isCollidable: true,
        texture: 'nature_wood'
      },
      // Ruins of walls
      {
        id: 'obj_ruined_wall_n',
        name: 'Ruined Wall North',
        type: 'box',
        position: { x: -4, y: 1, z: -4 },
        rotation: { x: 0, y: 0.4, z: 0 },
        scale: { x: 3, y: 2, z: 0.6 },
        color: '#71717a',
        metalness: 0.1,
        roughness: 0.85,
        opacity: 1,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0,
        isCollidable: true,
        texture: 'fantasy_cobble'
      },
      {
        id: 'obj_ruined_wall_s',
        name: 'Ruined Wall South',
        type: 'box',
        position: { x: 4, y: 1, z: 4 },
        rotation: { x: 0, y: 0.4, z: 0 },
        scale: { x: 3, y: 2, z: 0.6 },
        color: '#71717a',
        metalness: 0.1,
        roughness: 0.85,
        opacity: 1,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0,
        isCollidable: true,
        texture: 'fantasy_cobble'
      }
    ]
  },
  {
    id: 'vanguard_starbase',
    name: 'Vanguard Asteroid Mine',
    description: 'An industrial mineral extraction outpost located on an asteroid. Heavy blast doors, steel containers, and amber floodlights.',
    author: 'System Presets',
    theme: 'space',
    arenaRadius: 19,
    skyboxHue: 210, // Cold starlight
    skyboxBrightness: 3,
    fogColor: '#04070f',
    fogDensity: 0.015,
    spawnPoints: [
      { x: -10, y: 0, z: -10 },
      { x: 10, y: 0, z: 10 },
      { x: -10, y: 0, z: 10 },
      { x: 10, y: 0, z: -10 },
      { x: -13, y: 0, z: 0 },
      { x: 13, y: 0, z: 0 },
      { x: 0, y: 0, z: -13 },
      { x: 0, y: 0, z: 13 }
    ],
    lighting: {
      ambientColor: '#0a0d17',
      ambientIntensity: 0.6,
      directColor: '#fffbeb',
      directIntensity: 2.2,
      directPosition: { x: 12, y: 22, z: 6 },
      pointLights: [
        { id: 'shaft_light_1', color: '#ea580c', intensity: 3.5, distance: 15, decay: 1.3, position: { x: -6, y: 3, z: 5 } },
        { id: 'shaft_light_2', color: '#ea580c', intensity: 3.5, distance: 15, decay: 1.3, position: { x: 6, y: 3, z: -5 } }
      ]
    },
    objects: [
      // Core processing drill
      {
        id: 'obj_extractor',
        name: 'Meteorite Ore Extractor',
        type: 'cylinder',
        position: { x: 0, y: 2.5, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 2.6, y: 5, z: 2.6 },
        color: '#334155',
        metalness: 0.95,
        roughness: 0.05,
        opacity: 1,
        transparent: false,
        emissive: '#ca8a04',
        emissiveIntensity: 1.0,
        isCollidable: true,
        texture: 'space_alloy'
      },
      // Massive asteroid crag meteorite blocks
      {
        id: 'obj_asteroid_1',
        name: 'Asteroid Ore Cluster 1',
        type: 'box',
        position: { x: -6, y: 1.5, z: 5 },
        rotation: { x: 0, y: 0.6, z: 0 },
        scale: { x: 2.2, y: 3.0, z: 2.2 },
        color: '#1e293b',
        metalness: 0.3,
        roughness: 0.8,
        opacity: 1,
        transparent: false,
        emissive: '#ca8a04', // glowing amber mineral veins
        emissiveIntensity: 1.8,
        isCollidable: true,
        texture: 'space_meteorite'
      },
      {
        id: 'obj_asteroid_2',
        name: 'Asteroid Ore Cluster 2',
        type: 'box',
        position: { x: 6, y: 1.5, z: -5 },
        rotation: { x: 0, y: -0.4, z: 0 },
        scale: { x: 2.2, y: 3.0, z: 2.2 },
        color: '#1e293b',
        metalness: 0.3,
        roughness: 0.8,
        opacity: 1,
        transparent: false,
        emissive: '#ca8a04',
        emissiveIntensity: 1.8,
        isCollidable: true,
        texture: 'space_meteorite'
      },
      // Metallic cargo containers
      {
        id: 'obj_container_l',
        name: 'Freight Container Left',
        type: 'box',
        position: { x: -7, y: 1, z: -5 },
        rotation: { x: 0, y: 0.1, z: 0 },
        scale: { x: 1.8, y: 2.0, z: 3.5 },
        color: '#475569',
        metalness: 0.8,
        roughness: 0.3,
        opacity: 1,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0,
        isCollidable: true,
        texture: 'space_alloy'
      },
      {
        id: 'obj_container_r',
        name: 'Freight Container Right',
        type: 'box',
        position: { x: 7, y: 1, z: 5 },
        rotation: { x: 0, y: 0.1, z: 0 },
        scale: { x: 1.8, y: 2.0, z: 3.5 },
        color: '#475569',
        metalness: 0.8,
        roughness: 0.3,
        opacity: 1,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0,
        isCollidable: true,
        texture: 'space_alloy'
      },
      // Industrial hazard striped gates/partitions
      {
        id: 'obj_partition_n',
        name: 'Modular Containment Wall N',
        type: 'box',
        position: { x: 0, y: 1.5, z: -8 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 5, y: 3, z: 0.4 },
        color: '#3f3f46',
        metalness: 0.7,
        roughness: 0.4,
        opacity: 1,
        transparent: false,
        emissive: '#ca8a04',
        emissiveIntensity: 0.4,
        isCollidable: true,
        texture: 'city_concrete'
      },
      {
        id: 'obj_partition_s',
        name: 'Modular Containment Wall S',
        type: 'box',
        position: { x: 0, y: 1.5, z: 8 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 5, y: 3, z: 0.4 },
        color: '#3f3f46',
        metalness: 0.7,
        roughness: 0.4,
        opacity: 1,
        transparent: false,
        emissive: '#ca8a04',
        emissiveIntensity: 0.4,
        isCollidable: true,
        texture: 'city_concrete'
      }
    ]
  },
  {
    id: 'forerunner_canyon',
    name: 'Forerunner Canyon Plateau',
    description: 'A suspended rectangular forerunner arena hovering over a golden desert canyon at sunset. Features team-colored spires and a massive beacon tower.',
    author: 'Spartan Architect',
    theme: 'forerunner',
    mapShape: 'rectangular',
    arenaRadius: 20,
    skyboxHue: 35,
    skyboxBrightness: 7,
    fogColor: '#1d1510',
    fogDensity: 0.016,
    spawnPoints: [
      { x: -16, y: 0, z: -6 },
      { x: -16, y: 0, z: 6 },
      { x: -12, y: 0, z: -8 },
      { x: -12, y: 0, z: 8 },
      { x: 16, y: 0, z: -6 },
      { x: 16, y: 0, z: 6 },
      { x: 12, y: 0, z: -8 },
      { x: 12, y: 0, z: 8 }
    ],
    lighting: {
      ambientColor: '#18120e',
      ambientIntensity: 0.8,
      directColor: '#fef08a',
      directIntensity: 2.5,
      directPosition: { x: -10, y: 25, z: -10 },
      pointLights: [
        { id: 'blue_spire_nw', color: '#00ccff', intensity: 3.5, distance: 15, decay: 1.2, position: { x: -22, y: 4, z: -11 } },
        { id: 'blue_spire_sw', color: '#00ccff', intensity: 3.5, distance: 15, decay: 1.2, position: { x: -22, y: 4, z: 11 } },
        { id: 'red_spire_ne', color: '#ff3344', intensity: 3.5, distance: 15, decay: 1.2, position: { x: 22, y: 4, z: -11 } },
        { id: 'red_spire_se', color: '#ff3344', intensity: 3.5, distance: 15, decay: 1.2, position: { x: 22, y: 4, z: 11 } }
      ]
    },
    objects: [
      // Corner Spires (Collidable)
      // NW (Blue side, glows blue)
      {
        id: 'spire_nw',
        name: 'Forerunner Anchor Spire NW',
        type: 'cylinder',
        position: { x: -22, y: 4, z: -11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 2.0, y: 8.0, z: 2.0 },
        color: '#ca8a04',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 1.0,
        transparent: false,
        emissive: '#0088ff',
        emissiveIntensity: 2.0,
        isCollidable: true,
        texture: 'forerunner_gold'
      },
      // SW (Blue side, glows blue)
      {
        id: 'spire_sw',
        name: 'Forerunner Anchor Spire SW',
        type: 'cylinder',
        position: { x: -22, y: 4, z: 11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 2.0, y: 8.0, z: 2.0 },
        color: '#ca8a04',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 1.0,
        transparent: false,
        emissive: '#0088ff',
        emissiveIntensity: 2.0,
        isCollidable: true,
        texture: 'forerunner_gold'
      },
      // NE (Red side, glows red)
      {
        id: 'spire_ne',
        name: 'Forerunner Anchor Spire NE',
        type: 'cylinder',
        position: { x: 22, y: 4, z: -11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 2.0, y: 8.0, z: 2.0 },
        color: '#ca8a04',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 1.0,
        transparent: false,
        emissive: '#ff0033',
        emissiveIntensity: 2.0,
        isCollidable: true,
        texture: 'forerunner_gold'
      },
      // SE (Red side, glows red)
      {
        id: 'spire_se',
        name: 'Forerunner Anchor Spire SE',
        type: 'cylinder',
        position: { x: 22, y: 4, z: 11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 2.0, y: 8.0, z: 2.0 },
        color: '#ca8a04',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 1.0,
        transparent: false,
        emissive: '#ff0033',
        emissiveIntensity: 2.0,
        isCollidable: true,
        texture: 'forerunner_gold'
      },
      // Central Side Spires (Collidable)
      // Center North
      {
        id: 'spire_cn',
        name: 'Forerunner Pylon Center N',
        type: 'cylinder',
        position: { x: 0, y: 4, z: -11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.6, y: 8.0, z: 1.6 },
        color: '#1e293b',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#f59e0b',
        emissiveIntensity: 1.5,
        isCollidable: true,
        texture: 'forerunner_panel'
      },
      // Center South
      {
        id: 'spire_cs',
        name: 'Forerunner Pylon Center S',
        type: 'cylinder',
        position: { x: 0, y: 4, z: 11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.6, y: 8.0, z: 1.6 },
        color: '#1e293b',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#f59e0b',
        emissiveIntensity: 1.5,
        isCollidable: true,
        texture: 'forerunner_panel'
      },
      // Defensive Goal Obstacles (Collidable)
      // West Goal Block
      {
        id: 'barrier_w',
        name: 'Forerunner Buffer W',
        type: 'box',
        position: { x: -17, y: 1.0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 2.0, z: 4.0 },
        color: '#1e293b',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: true,
        texture: 'forerunner_panel'
      },
      // East Goal Block
      {
        id: 'barrier_e',
        name: 'Forerunner Buffer E',
        type: 'box',
        position: { x: 17, y: 1.0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 2.0, z: 4.0 },
        color: '#1e293b',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: true,
        texture: 'forerunner_panel'
      },
      // BACKGROUND SCENERY (Non-collidable)
      // Majestic central beacon tower (with glowing yellow top tip)
      {
        id: 'bg_beacon_tower',
        name: 'Majestic Beacon Tower',
        type: 'cylinder',
        position: { x: 0, y: 20, z: -35 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 3.0, y: 40.0, z: 3.0 },
        color: '#1f2937',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 1.0,
        transparent: false,
        emissive: '#fbbf24',
        emissiveIntensity: 3.0,
        isCollidable: false,
        texture: 'forerunner_gold'
      },
      // Left Canyon Pillar
      {
        id: 'bg_pillar_l',
        name: 'Canyon Anchor Left',
        type: 'cylinder',
        position: { x: -45, y: 15, z: -25 },
        rotation: { x: 0.15, y: 0, z: 0.25 },
        scale: { x: 4.0, y: 30.0, z: 4.0 },
        color: '#374151',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: false,
        texture: 'forerunner_panel'
      },
      // Right Canyon Pillar
      {
        id: 'bg_pillar_r',
        name: 'Canyon Anchor Right',
        type: 'cylinder',
        position: { x: 45, y: 15, z: -25 },
        rotation: { x: 0.15, y: 0, z: -0.25 },
        scale: { x: 4.0, y: 30.0, z: 4.0 },
        color: '#374151',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: false,
        texture: 'forerunner_panel'
      }
    ]
  },
  {
    id: 'synthwave_grid_arena',
    name: 'Neon Outrun Grid',
    description: 'A suspended rectangular retro holodeck hovering over a glowing cyber city at twilight. Features glowing neon palm trees, background light beams, and a colossal striped sunset sun.',
    author: 'Outrun Architect',
    theme: 'synthwave',
    mapShape: 'rectangular',
    arenaRadius: 20,
    skyboxHue: 310,
    skyboxBrightness: 7,
    fogColor: '#0a0518',
    fogDensity: 0.012,
    spawnPoints: [
      { x: -16, y: 0, z: -6 },
      { x: -16, y: 0, z: 6 },
      { x: -12, y: 0, z: -8 },
      { x: -12, y: 0, z: 8 },
      { x: 16, y: 0, z: -6 },
      { x: 16, y: 0, z: 6 },
      { x: 12, y: 0, z: -8 },
      { x: 12, y: 0, z: 8 }
    ],
    lighting: {
      ambientColor: '#0f051d',
      ambientIntensity: 0.95,
      directColor: '#f43f5e',
      directIntensity: 2.4,
      directPosition: { x: -10, y: 25, z: -10 },
      pointLights: [
        { id: 'blue_goal_glow', color: '#00ffff', intensity: 4.0, distance: 18, decay: 1.2, position: { x: -18, y: 2, z: 0 } },
        { id: 'red_goal_glow', color: '#ff0055', intensity: 4.0, distance: 18, decay: 1.2, position: { x: 18, y: 2, z: 0 } }
      ]
    },
    objects: [
      // NW (Blue side, glows cyan)
      {
        id: 'neon_pillar_nw',
        name: 'Neon Beacon NW',
        type: 'cylinder',
        position: { x: -22, y: 4, z: -11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.5, y: 8.0, z: 1.5 },
        color: '#00ffff',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.9,
        transparent: true,
        emissive: '#06b6d4',
        emissiveIntensity: 2.5,
        isCollidable: true,
        texture: 'synthwave_neon_laser'
      },
      // SW (Blue side, glows cyan)
      {
        id: 'neon_pillar_sw',
        name: 'Neon Beacon SW',
        type: 'cylinder',
        position: { x: -22, y: 4, z: 11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.5, y: 8.0, z: 1.5 },
        color: '#00ffff',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.9,
        transparent: true,
        emissive: '#06b6d4',
        emissiveIntensity: 2.5,
        isCollidable: true,
        texture: 'synthwave_neon_laser'
      },
      // NE (Red side, glows pink)
      {
        id: 'neon_pillar_ne',
        name: 'Neon Beacon NE',
        type: 'cylinder',
        position: { x: 22, y: 4, z: -11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.5, y: 8.0, z: 1.5 },
        color: '#ff0055',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.9,
        transparent: true,
        emissive: '#ff0055',
        emissiveIntensity: 2.5,
        isCollidable: true,
        texture: 'synthwave_neon_laser'
      },
      // SE (Red side, glows pink)
      {
        id: 'neon_pillar_se',
        name: 'Neon Beacon SE',
        type: 'cylinder',
        position: { x: 22, y: 4, z: 11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.5, y: 8.0, z: 1.5 },
        color: '#ff0055',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.9,
        transparent: true,
        emissive: '#ff0055',
        emissiveIntensity: 2.5,
        isCollidable: true,
        texture: 'synthwave_neon_laser'
      },
      // Center North (Glowing yellow)
      {
        id: 'neon_pillar_cn',
        name: 'Neon Grid Pylon N',
        type: 'cylinder',
        position: { x: 0, y: 4, z: -11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 8.0, z: 1.2 },
        color: '#eab308',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.9,
        transparent: true,
        emissive: '#eab308',
        emissiveIntensity: 2.0,
        isCollidable: true,
        texture: 'synthwave_neon_laser'
      },
      // Center South (Glowing yellow)
      {
        id: 'neon_pillar_cs',
        name: 'Neon Grid Pylon S',
        type: 'cylinder',
        position: { x: 0, y: 4, z: 11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 8.0, z: 1.2 },
        color: '#eab308',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.9,
        transparent: true,
        emissive: '#eab308',
        emissiveIntensity: 2.0,
        isCollidable: true,
        texture: 'synthwave_neon_laser'
      },
      // Goal buffers
      {
        id: 'grid_barrier_w',
        name: 'Blue Goal Buffer',
        type: 'box',
        position: { x: -17, y: 1.0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 2.0, z: 4.0 },
        color: '#00ffff',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 0.8,
        transparent: true,
        emissive: '#06b6d4',
        emissiveIntensity: 1.5,
        isCollidable: true,
        texture: 'synthwave_grid'
      },
      {
        id: 'grid_barrier_e',
        name: 'Red Goal Buffer',
        type: 'box',
        position: { x: 17, y: 1.0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 2.0, z: 4.0 },
        color: '#ff0055',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 0.8,
        transparent: true,
        emissive: '#ff0055',
        emissiveIntensity: 1.5,
        isCollidable: true,
        texture: 'synthwave_grid'
      }
    ]
  },
  {
    id: 'rainy_industrial_streets',
    name: 'Rainy Cyber Streets',
    description: 'A dark, rain-slicked industrial street court under warm sodium spotlights, framed by towering skyscrapers and a giant neon dog billboard.',
    author: 'Urban Architect',
    theme: 'rainy_streets',
    mapShape: 'rectangular',
    arenaRadius: 20,
    skyboxHue: 210,
    skyboxBrightness: 2,
    fogColor: '#06080c',
    fogDensity: 0.024,
    spawnPoints: [
      { x: -16, y: 0, z: -6 },
      { x: -16, y: 0, z: 6 },
      { x: -12, y: 0, z: -8 },
      { x: -12, y: 0, z: 8 },
      { x: 16, y: 0, z: -6 },
      { x: 16, y: 0, z: 6 },
      { x: 12, y: 0, z: -8 },
      { x: 12, y: 0, z: 8 }
    ],
    lighting: {
      ambientColor: '#0f1118',
      ambientIntensity: 0.7,
      directColor: '#fed7aa',
      directIntensity: 1.8,
      directPosition: { x: -8, y: 22, z: -8 },
      pointLights: [
        { id: 'street_l1', color: '#ff7700', intensity: 3.5, distance: 15, decay: 1.2, position: { x: -20, y: 3.5, z: -8 } },
        { id: 'street_l2', color: '#ff7700', intensity: 3.5, distance: 15, decay: 1.2, position: { x: -20, y: 3.5, z: 0 } },
        { id: 'street_l3', color: '#ff7700', intensity: 3.5, distance: 15, decay: 1.2, position: { x: -20, y: 3.5, z: 8 } },
        { id: 'street_r1', color: '#ff7700', intensity: 3.5, distance: 15, decay: 1.2, position: { x: 20, y: 3.5, z: -8 } },
        { id: 'street_r2', color: '#ff7700', intensity: 3.5, distance: 15, decay: 1.2, position: { x: 20, y: 3.5, z: 0 } },
        { id: 'street_r3', color: '#ff7700', intensity: 3.5, distance: 15, decay: 1.2, position: { x: 20, y: 3.5, z: 8 } }
      ]
    },
    objects: [
      {
        id: 'rainy_barrier_w',
        name: 'Blue Street Buffer',
        type: 'box',
        position: { x: -17, y: 1.0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 2.0, z: 4.0 },
        color: '#ff7700',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#ea580c',
        emissiveIntensity: 1.5,
        isCollidable: true,
        texture: 'rainy_streets_neon_glow'
      },
      {
        id: 'rainy_barrier_e',
        name: 'Red Street Buffer',
        type: 'box',
        position: { x: 17, y: 1.0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 2.0, z: 4.0 },
        color: '#ff7700',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#ea580c',
        emissiveIntensity: 1.5,
        isCollidable: true,
        texture: 'rainy_streets_neon_glow'
      },
      {
        id: 'rainy_crate_nw',
        name: 'Heavy Street Cargo NW',
        type: 'box',
        position: { x: -6, y: 1.0, z: -5 },
        rotation: { x: 0, y: 0.4, z: 0 },
        scale: { x: 2.0, y: 2.0, z: 2.0 },
        color: '#ff7700',
        metalness: 0.7,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#ea580c',
        emissiveIntensity: 1.2,
        isCollidable: true,
        texture: 'rainy_streets_neon_glow'
      },
      {
        id: 'rainy_crate_se',
        name: 'Heavy Street Cargo SE',
        type: 'box',
        position: { x: 6, y: 1.0, z: 5 },
        rotation: { x: 0, y: -0.3, z: 0 },
        scale: { x: 2.0, y: 2.0, z: 2.0 },
        color: '#ff7700',
        metalness: 0.7,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#ea580c',
        emissiveIntensity: 1.2,
        isCollidable: true,
        texture: 'rainy_streets_neon_glow'
      }
    ]
  },
  {
    id: 'winter_glacier_rink',
    name: 'Glacier Hockey Rink',
    description: 'A pristine ice hockey arena surrounded by frozen glaciers, tall snowy pines, and gentle falling snow. Watch your step on the slick glacier ice!',
    author: 'Olympic Architect',
    theme: 'winter_rink',
    mapShape: 'rectangular',
    arenaRadius: 20,
    skyboxHue: 200,
    skyboxBrightness: 15,
    fogColor: '#e0f2fe',
    fogDensity: 0.02,
    spawnPoints: [
      { x: -16, y: 0, z: -6 },
      { x: -16, y: 0, z: 6 },
      { x: -12, y: 0, z: -8 },
      { x: -12, y: 0, z: 8 },
      { x: 16, y: 0, z: -6 },
      { x: 16, y: 0, z: 6 },
      { x: 12, y: 0, z: -8 },
      { x: 12, y: 0, z: 8 }
    ],
    lighting: {
      ambientColor: '#f0f9ff',
      ambientIntensity: 1.0,
      directColor: '#ffffff',
      directIntensity: 2.5,
      directPosition: { x: -10, y: 25, z: -10 },
      pointLights: [
        { id: 'blue_goal_glow', color: '#60a5fa', intensity: 4.5, distance: 18, decay: 1.2, position: { x: -19, y: 2, z: 0 } },
        { id: 'red_goal_glow', color: '#ef4444', intensity: 4.5, distance: 18, decay: 1.2, position: { x: 19, y: 2, z: 0 } }
      ]
    },
    objects: [
      // Corner Posts (White metal pillars)
      {
        id: 'post_nw',
        name: 'Anchor Pillar NW',
        type: 'cylinder',
        position: { x: -24, y: 2.5, z: -12 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 0.6, y: 5.0, z: 0.6 },
        color: '#cbd5e1',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: true,
        texture: 'none'
      },
      {
        id: 'post_sw',
        name: 'Anchor Pillar SW',
        type: 'cylinder',
        position: { x: -24, y: 2.5, z: 12 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 0.6, y: 5.0, z: 0.6 },
        color: '#cbd5e1',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: true,
        texture: 'none'
      },
      {
        id: 'post_ne',
        name: 'Anchor Pillar NE',
        type: 'cylinder',
        position: { x: 24, y: 2.5, z: -12 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 0.6, y: 5.0, z: 0.6 },
        color: '#cbd5e1',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: true,
        texture: 'none'
      },
      {
        id: 'post_se',
        name: 'Anchor Pillar SE',
        type: 'cylinder',
        position: { x: 24, y: 2.5, z: 12 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 0.6, y: 5.0, z: 0.6 },
        color: '#cbd5e1',
        metalness: 0.8,
        roughness: 0.2,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: true,
        texture: 'none'
      },
      
      // Hockey Goals (Red frame, open mesh design replicated by placing net block)
      {
        id: 'goal_w',
        name: 'West Goal Frame',
        type: 'box',
        position: { x: -19, y: 1.0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.5, y: 2.0, z: 4.0 },
        color: '#ef4444',
        metalness: 0.6,
        roughness: 0.4,
        opacity: 1.0,
        transparent: false,
        emissive: '#ef4444',
        emissiveIntensity: 0.2,
        isCollidable: true,
        texture: 'none'
      },
      {
        id: 'goal_e',
        name: 'East Goal Frame',
        type: 'box',
        position: { x: 19, y: 1.0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.5, y: 2.0, z: 4.0 },
        color: '#ef4444',
        metalness: 0.6,
        roughness: 0.4,
        opacity: 1.0,
        transparent: false,
        emissive: '#ef4444',
        emissiveIntensity: 0.2,
        isCollidable: true,
        texture: 'none'
      },

      // Outer Rink Perimeter Boards: Lower Opaque White Board (y = 0.4, height = 0.8)
      {
        id: 'board_low_n',
        name: 'Lower Board North',
        type: 'box',
        position: { x: 0, y: 0.4, z: -12 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 48.0, y: 0.8, z: 0.1 },
        color: '#f8fafc',
        metalness: 0.3,
        roughness: 0.7,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: true,
        texture: 'none'
      },
      {
        id: 'board_low_s',
        name: 'Lower Board South',
        type: 'box',
        position: { x: 0, y: 0.4, z: 12 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 48.0, y: 0.8, z: 0.1 },
        color: '#f8fafc',
        metalness: 0.3,
        roughness: 0.7,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: true,
        texture: 'none'
      },
      {
        id: 'board_low_w',
        name: 'Lower Board West',
        type: 'box',
        position: { x: -24, y: 0.4, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 0.1, y: 0.8, z: 24.0 },
        color: '#f8fafc',
        metalness: 0.3,
        roughness: 0.7,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: true,
        texture: 'none'
      },
      {
        id: 'board_low_e',
        name: 'Lower Board East',
        type: 'box',
        position: { x: 24, y: 0.4, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 0.1, y: 0.8, z: 24.0 },
        color: '#f8fafc',
        metalness: 0.3,
        roughness: 0.7,
        opacity: 1.0,
        transparent: false,
        emissive: '#000000',
        emissiveIntensity: 0.0,
        isCollidable: true,
        texture: 'none'
      },

      // Outer Rink Perimeter Boards: Upper Translucent Acrylic Glass (y = 1.5, height = 1.4)
      {
        id: 'board_glass_n',
        name: 'Glass Board North',
        type: 'box',
        position: { x: 0, y: 1.5, z: -12 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 48.0, y: 1.4, z: 0.1 },
        color: '#93c5fd',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.6,
        transparent: true,
        emissive: '#60a5fa',
        emissiveIntensity: 0.2,
        isCollidable: true,
        texture: 'winter_glacier_glass'
      },
      {
        id: 'board_glass_s',
        name: 'Glass Board South',
        type: 'box',
        position: { x: 0, y: 1.5, z: 12 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 48.0, y: 1.4, z: 0.1 },
        color: '#93c5fd',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.6,
        transparent: true,
        emissive: '#60a5fa',
        emissiveIntensity: 0.2,
        isCollidable: true,
        texture: 'winter_glacier_glass'
      },
      {
        id: 'board_glass_w',
        name: 'Glass Board West',
        type: 'box',
        position: { x: -24, y: 1.5, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 0.1, y: 1.4, z: 24.0 },
        color: '#93c5fd',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.6,
        transparent: true,
        emissive: '#60a5fa',
        emissiveIntensity: 0.2,
        isCollidable: true,
        texture: 'winter_glacier_glass'
      },
      {
        id: 'board_glass_e',
        name: 'Glass Board East',
        type: 'box',
        position: { x: 24, y: 1.5, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 0.1, y: 1.4, z: 24.0 },
        color: '#93c5fd',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.6,
        transparent: true,
        emissive: '#60a5fa',
        emissiveIntensity: 0.2,
        isCollidable: true,
        texture: 'winter_glacier_glass'
      }
    ]
  },
  {
    id: 'championship_stadium',
    name: 'Championship Stadium',
    description: 'An elite, high-tech steel arena framed by cheering stands, brilliant stadium spotlights, a massive center scoreboard, and glowing team boundary lines.',
    author: 'Spartan Architect',
    theme: 'grifball_stadium',
    mapShape: 'rectangular',
    arenaRadius: 20,
    skyboxHue: 220,
    skyboxBrightness: 4,
    fogColor: '#0b0c10',
    fogDensity: 0.015,
    spawnPoints: [
      { x: -16, y: 0, z: -6 },
      { x: -16, y: 0, z: 6 },
      { x: -12, y: 0, z: -8 },
      { x: -12, y: 0, z: 8 },
      { x: 16, y: 0, z: -6 },
      { x: 16, y: 0, z: 6 },
      { x: 12, y: 0, z: -8 },
      { x: 12, y: 0, z: 8 }
    ],
    lighting: {
      ambientColor: '#1f2833',
      ambientIntensity: 0.85,
      directColor: '#ffffff',
      directIntensity: 2.8,
      directPosition: { x: -8, y: 25, z: -8 },
      pointLights: [
        { id: 'stadium_blue_light_nw', color: '#00ffff', intensity: 4.5, distance: 18, decay: 1.2, position: { x: -20, y: 4, z: -10 } },
        { id: 'stadium_blue_light_sw', color: '#00ffff', intensity: 4.5, distance: 18, decay: 1.2, position: { x: -20, y: 4, z: 10 } },
        { id: 'stadium_red_light_ne', color: '#ff3344', intensity: 4.5, distance: 18, decay: 1.2, position: { x: 20, y: 4, z: -10 } },
        { id: 'stadium_red_light_se', color: '#ff3344', intensity: 4.5, distance: 18, decay: 1.2, position: { x: 20, y: 4, z: 10 } }
      ]
    },
    objects: [
      // Decorative goal barriers/buffers
      {
        id: 'stadium_barrier_w',
        name: 'Blue Goal Buffer',
        type: 'box',
        position: { x: -17, y: 1.0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 2.0, z: 4.0 },
        color: '#00ffff',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.9,
        transparent: true,
        emissive: '#0088ff',
        emissiveIntensity: 1.5,
        isCollidable: true,
        texture: 'stadium_steel_grid'
      },
      {
        id: 'stadium_barrier_e',
        name: 'Red Goal Buffer',
        type: 'box',
        position: { x: 17, y: 1.0, z: 0 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 2.0, z: 4.0 },
        color: '#ff3344',
        metalness: 0.9,
        roughness: 0.1,
        opacity: 0.9,
        transparent: true,
        emissive: '#ff0033',
        emissiveIntensity: 1.5,
        isCollidable: true,
        texture: 'stadium_steel_grid'
      },
      // Corner glowing beacons
      {
        id: 'stadium_beacon_nw',
        name: 'Championship Pillar NW',
        type: 'cylinder',
        position: { x: -22, y: 3.5, z: -11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 7.0, z: 1.2 },
        color: '#0f172a',
        metalness: 0.95,
        roughness: 0.05,
        opacity: 1,
        transparent: false,
        emissive: '#00ccff',
        emissiveIntensity: 2.0,
        isCollidable: true,
        texture: 'stadium_steel_grid'
      },
      {
        id: 'stadium_beacon_sw',
        name: 'Championship Pillar SW',
        type: 'cylinder',
        position: { x: -22, y: 3.5, z: 11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 7.0, z: 1.2 },
        color: '#0f172a',
        metalness: 0.95,
        roughness: 0.05,
        opacity: 1,
        transparent: false,
        emissive: '#00ccff',
        emissiveIntensity: 2.0,
        isCollidable: true,
        texture: 'stadium_steel_grid'
      },
      {
        id: 'stadium_beacon_ne',
        name: 'Championship Pillar NE',
        type: 'cylinder',
        position: { x: 22, y: 3.5, z: -11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 7.0, z: 1.2 },
        color: '#0f172a',
        metalness: 0.95,
        roughness: 0.05,
        opacity: 1,
        transparent: false,
        emissive: '#ff0033',
        emissiveIntensity: 2.0,
        isCollidable: true,
        texture: 'stadium_steel_grid'
      },
      {
        id: 'stadium_beacon_se',
        name: 'Championship Pillar SE',
        type: 'cylinder',
        position: { x: 22, y: 3.5, z: 11 },
        rotation: { x: 0, y: 0, z: 0 },
        scale: { x: 1.2, y: 7.0, z: 1.2 },
        color: '#0f172a',
        metalness: 0.95,
        roughness: 0.05,
        opacity: 1,
        transparent: false,
        emissive: '#ff0033',
        emissiveIntensity: 2.0,
        isCollidable: true,
        texture: 'stadium_steel_grid'
      }
    ]
  }
];


