/* eslint-disable */
// Generated by src/tools/v3Mesh2MotionImporter.ts. Do not edit by hand.
// Source Mesh2Motion GLB files stay private/local; this file contains sanitized TPose armor rig data only.
export const V3_MESH2MOTION_ARMOR_RIG = {
  "schemaVersion": "v3-mesh2motion-armor-rig/v1",
  "version": 1,
  "source": {
    "kind": "mesh2motion-glb",
    "fileName": "exported-model.glb",
    "sha256": "30c44e6e71cf98322cad6a75978bdf36d0746fb060ac9981c42982c2c7bdc8f2",
    "generator": "THREE.GLTFExporter r183"
  },
  "skeleton": {
    "sourceJointCount": 56,
    "joints": [
      {
        "name": "root",
        "parent": "Skinned Mesh 28",
        "restLocalPosition": [
          0,
          0,
          0
        ],
        "restWorldPosition": [
          0,
          0,
          0
        ],
        "restWorldQuaternion": [
          -0.707106781,
          0,
          0,
          0.707106781
        ],
        "restLocalQuaternion": [
          -0.707106781,
          0,
          0,
          0.707106781
        ]
      },
      {
        "name": "pelvis",
        "parent": "root",
        "restLocalPosition": [
          0,
          0.047786,
          0.874363
        ],
        "restWorldPosition": [
          0,
          0.874363,
          -0.047786
        ],
        "restWorldQuaternion": [
          0.12584079,
          1.5e-8,
          2e-9,
          0.99205045
        ],
        "restLocalQuaternion": [
          0.790468476,
          9e-9,
          1.2e-8,
          0.612502725
        ]
      },
      {
        "name": "spine_01",
        "parent": "pelvis",
        "restLocalPosition": [
          0,
          0.099171,
          0
        ],
        "restWorldPosition": [
          0,
          0.970394,
          -0.023025
        ],
        "restWorldQuaternion": [
          0.061388777,
          1.33e-7,
          8e-9,
          0.99811393
        ],
        "restLocalQuaternion": [
          -0.064702681,
          1.19e-7,
          -1e-8,
          0.997904586
        ]
      },
      {
        "name": "spine_02",
        "parent": "spine_01",
        "restLocalPosition": [
          0,
          0.118307,
          0
        ],
        "restWorldPosition": [
          0,
          1.087808,
          -0.008527
        ],
        "restWorldQuaternion": [
          -0.015928956,
          7e-8,
          -1e-9,
          0.999873126
        ],
        "restLocalQuaternion": [
          -0.077279901,
          -6.3e-8,
          -1.6e-8,
          0.997009437
        ]
      },
      {
        "name": "spine_03",
        "parent": "spine_02",
        "restLocalPosition": [
          0,
          0.134747,
          0
        ],
        "restWorldPosition": [
          0,
          1.222487,
          -0.012819
        ],
        "restWorldQuaternion": [
          -0.113419601,
          6.5e-8,
          -7e-9,
          0.993547178
        ],
        "restLocalQuaternion": [
          -0.097579042,
          -5e-9,
          -1.3e-8,
          0.995227778
        ]
      },
      {
        "name": "neck_01",
        "parent": "spine_03",
        "restLocalPosition": [
          0,
          0.166728,
          0
        ],
        "restWorldPosition": [
          0,
          1.384926,
          -0.050396
        ],
        "restWorldQuaternion": [
          0.226862534,
          5.9e-8,
          1.4e-8,
          0.973926789
        ],
        "restLocalQuaternion": [
          0.335861019,
          -5e-9,
          4.2e-8,
          0.941911554
        ]
      },
      {
        "name": "head",
        "parent": "neck_01",
        "restLocalPosition": [
          0,
          0.125965,
          0
        ],
        "restWorldPosition": [
          0,
          1.497925,
          0.005268
        ],
        "restWorldQuaternion": [
          0.01626073,
          7.5e-8,
          1e-9,
          0.999867786
        ],
        "restLocalQuaternion": [
          -0.210995779,
          1.5e-8,
          -2.9e-8,
          0.977486972
        ]
      },
      {
        "name": "head_leaf",
        "parent": "head",
        "restLocalPosition": [
          0,
          0.066586,
          0
        ],
        "restWorldPosition": [
          0,
          1.564475,
          0.007433
        ],
        "restWorldQuaternion": [
          1.75e-7,
          1.19e-7,
          0,
          1
        ],
        "restLocalQuaternion": [
          -0.016260555,
          4.4e-8,
          -3e-9,
          0.999867788
        ]
      },
      {
        "name": "clavicle_l",
        "parent": "spine_03",
        "restLocalPosition": [
          0.017932,
          0.117443,
          0.100665
        ],
        "restWorldPosition": [
          0.017932,
          1.359596,
          0.058787
        ],
        "restWorldQuaternion": [
          -0.659670142,
          -0.29440746,
          -0.321670063,
          0.612117572
        ],
        "restLocalQuaternion": [
          -0.585987253,
          -0.256024055,
          -0.352985998,
          0.682987194
        ]
      },
      {
        "name": "upperarm_l",
        "parent": "clavicle_l",
        "restLocalPosition": [
          0.059431,
          0.21374,
          0.002494
        ],
        "restWorldPosition": [
          0.222113,
          1.345247,
          -0.026811
        ],
        "restWorldQuaternion": [
          -0.006307458,
          0.005791519,
          -0.738173076,
          0.674557028
        ],
        "restLocalQuaternion": [
          0.221937606,
          0.68706153,
          -0.229186454,
          0.652812165
        ]
      },
      {
        "name": "lowerarm_l",
        "parent": "upperarm_l",
        "restLocalPosition": [
          -0.012218,
          0.241785,
          0.01272
        ],
        "restWorldPosition": [
          0.464199,
          1.335684,
          -0.018236
        ],
        "restWorldQuaternion": [
          0.005268804,
          -0.00690651,
          -0.738163046,
          0.674566422
        ],
        "restLocalQuaternion": [
          0.017182193,
          -0.000020378,
          6.52e-7,
          0.999852375
        ]
      },
      {
        "name": "hand_l",
        "parent": "lowerarm_l",
        "restLocalPosition": [
          -0.001011,
          0.257463,
          0.004936
        ],
        "restWorldPosition": [
          0.72059,
          1.31358,
          -0.008847
        ],
        "restWorldQuaternion": [
          -0.00054593,
          -0.000543504,
          -0.73819514,
          0.674586794
        ],
        "restLocalQuaternion": [
          -0.008619688,
          2e-8,
          2.2e-8,
          0.99996285
        ]
      },
      {
        "name": "index_01_l",
        "parent": "hand_l",
        "restLocalPosition": [
          0.00204,
          0.12747,
          0.047758
        ],
        "restWorldPosition": [
          0.847364,
          1.300167,
          0.038923
        ],
        "restWorldQuaternion": [
          -0.5215988,
          -0.476622149,
          0.522367082,
          -0.477387317
        ],
        "restLocalQuaternion": [
          2.2e-7,
          0.707109344,
          -2.27e-7,
          0.707104218
        ]
      },
      {
        "name": "index_02_l",
        "parent": "index_01_l",
        "restLocalPosition": [
          -0.009715,
          0.021581,
          0.00786
        ],
        "restWorldPosition": [
          0.868152,
          1.290414,
          0.048651
        ],
        "restWorldQuaternion": [
          -0.521598691,
          -0.476622056,
          0.522367191,
          -0.477387409
        ],
        "restLocalQuaternion": [
          0,
          -2.02e-7,
          -7e-9,
          1
        ]
      },
      {
        "name": "index_03_l",
        "parent": "index_02_l",
        "restLocalPosition": [
          -0.004119,
          0.016615,
          0.024528
        ],
        "restWorldPosition": [
          0.882495,
          1.264498,
          0.052809
        ],
        "restWorldQuaternion": [
          -0.521598691,
          -0.476622056,
          0.522367191,
          -0.477387409
        ],
        "restLocalQuaternion": [
          0,
          0,
          0,
          1
        ]
      },
      {
        "name": "middle_01_l",
        "parent": "hand_l",
        "restLocalPosition": [
          0.006063,
          0.134645,
          0.019316
        ],
        "restWorldPosition": [
          0.854147,
          1.295471,
          0.010487
        ],
        "restWorldQuaternion": [
          -0.510195139,
          -0.488809711,
          0.533497705,
          -0.464915246
        ],
        "restLocalQuaternion": [
          -0.016702197,
          0.706912083,
          -0.016702769,
          0.706906897
        ]
      },
      {
        "name": "middle_02_l",
        "parent": "middle_01_l",
        "restLocalPosition": [
          -0.006743,
          0.023216,
          0.012649
        ],
        "restWorldPosition": [
          0.876424,
          1.280769,
          0.016146
        ],
        "restWorldQuaternion": [
          -0.510934312,
          -0.488036824,
          0.532793489,
          -0.465722326
        ],
        "restLocalQuaternion": [
          -9e-9,
          -2.01e-7,
          0.001513614,
          0.999998854
        ]
      },
      {
        "name": "middle_03_l",
        "parent": "middle_02_l",
        "restLocalPosition": [
          -0.006354,
          0.021663,
          0.012171
        ],
        "restWorldPosition": [
          0.897165,
          1.266686,
          0.021556
        ],
        "restWorldQuaternion": [
          -0.51038267,
          -0.488613694,
          0.533319264,
          -0.465120146
        ],
        "restLocalQuaternion": [
          8e-9,
          0,
          -0.001129667,
          0.999999362
        ]
      },
      {
        "name": "pinky_01_l",
        "parent": "hand_l",
        "restLocalPosition": [
          0.019206,
          0.10714,
          -0.034147
        ],
        "restWorldPosition": [
          0.825568,
          1.284771,
          -0.042957
        ],
        "restWorldQuaternion": [
          -0.505326724,
          -0.493840975,
          0.538078193,
          -0.459606192
        ],
        "restLocalQuaternion": [
          -0.023705808,
          0.706711882,
          -0.02370643,
          0.706706697
        ]
      },
      {
        "name": "pinky_02_l",
        "parent": "pinky_01_l",
        "restLocalPosition": [
          0.003217,
          0.024991,
          0.008783
        ],
        "restWorldPosition": [
          0.849397,
          1.273794,
          -0.047826
        ],
        "restWorldQuaternion": [
          -0.504914431,
          -0.494262302,
          0.538461558,
          -0.45915721
        ],
        "restLocalQuaternion": [
          5e-9,
          -2e-7,
          -0.0008343,
          0.999999652
        ]
      },
      {
        "name": "pinky_03_l",
        "parent": "pinky_02_l",
        "restLocalPosition": [
          -0.001478,
          0.020492,
          0.017966
        ],
        "restWorldPosition": [
          0.868244,
          1.254055,
          -0.04773
        ],
        "restWorldQuaternion": [
          -0.505215658,
          -0.493954397,
          0.538181536,
          -0.459485395
        ],
        "restLocalQuaternion": [
          -4e-9,
          0,
          0.00060964,
          0.999999814
        ]
      },
      {
        "name": "ring_01_l",
        "parent": "hand_l",
        "restLocalPosition": [
          0.015727,
          0.139632,
          -0.010842
        ],
        "restWorldPosition": [
          0.858243,
          1.285352,
          -0.019656
        ],
        "restWorldQuaternion": [
          -0.513030836,
          -0.48583262,
          0.530783344,
          -0.468011825
        ],
        "restLocalQuaternion": [
          -0.012588433,
          0.706997276,
          -0.012588983,
          0.70699215
        ]
      },
      {
        "name": "ring_02_l",
        "parent": "ring_01_l",
        "restLocalPosition": [
          -0.003345,
          0.026352,
          0.008811
        ],
        "restWorldPosition": [
          0.883799,
          1.274203,
          -0.017235
        ],
        "restWorldQuaternion": [
          -0.51303665,
          -0.485826274,
          0.530777744,
          -0.46801839
        ],
        "restLocalQuaternion": [
          0,
          -2.01e-7,
          0.000012185,
          1
        ]
      },
      {
        "name": "ring_03_l",
        "parent": "ring_02_l",
        "restLocalPosition": [
          -0.004011,
          0.019877,
          0.019299
        ],
        "restWorldPosition": [
          0.901991,
          1.253189,
          -0.013903
        ],
        "restWorldQuaternion": [
          -0.512517953,
          -0.486373437,
          0.531276851,
          -0.467451746
        ],
        "restLocalQuaternion": [
          7e-9,
          0,
          -0.001067064,
          0.999999431
        ]
      },
      {
        "name": "thumb_01_l",
        "parent": "hand_l",
        "restLocalPosition": [
          0.024673,
          0.056413,
          0.05975
        ],
        "restWorldPosition": [
          0.774562,
          1.284029,
          0.050945
        ],
        "restWorldQuaternion": [
          0.86494283,
          0.45546288,
          0.097301126,
          0.18697582
        ],
        "restLocalQuaternion": [
          0.247413485,
          0.94579434,
          0.203441246,
          0.053584456
        ]
      },
      {
        "name": "thumb_02_l",
        "parent": "thumb_01_l",
        "restLocalPosition": [
          0.00297,
          0.032447,
          -0.008642
        ],
        "restWorldPosition": [
          0.797701,
          1.27179,
          0.072183
        ],
        "restWorldQuaternion": [
          0.864946576,
          0.455394089,
          0.097307914,
          0.187122459
        ],
        "restLocalQuaternion": [
          -0.000135919,
          -0.000074144,
          0.000048208,
          0.999999987
        ]
      },
      {
        "name": "thumb_03_l",
        "parent": "thumb_02_l",
        "restLocalPosition": [
          -0.000276,
          0.03114,
          0.000609
        ],
        "restWorldPosition": [
          0.821149,
          1.255376,
          0.084469
        ],
        "restWorldQuaternion": [
          0.864740896,
          0.455896867,
          0.097164636,
          0.186923149
        ],
        "restLocalQuaternion": [
          0.000248076,
          0.000080932,
          -0.000535957,
          0.999999822
        ]
      },
      {
        "name": "clavicle_r",
        "parent": "spine_03",
        "restLocalPosition": [
          -0.017932,
          0.117443,
          0.100665
        ],
        "restWorldPosition": [
          -0.017932,
          1.359596,
          0.058787
        ],
        "restWorldQuaternion": [
          -0.659670104,
          0.29440753,
          0.321670108,
          0.612117555
        ],
        "restLocalQuaternion": [
          -0.585987264,
          0.25602403,
          0.352985975,
          0.682987206
        ]
      },
      {
        "name": "upperarm_r",
        "parent": "clavicle_r",
        "restLocalPosition": [
          -0.059431,
          0.21374,
          0.002494
        ],
        "restWorldPosition": [
          -0.222113,
          1.345247,
          -0.026811
        ],
        "restWorldQuaternion": [
          -0.006307414,
          -0.005791612,
          0.738173066,
          0.674557038
        ],
        "restLocalQuaternion": [
          0.221937535,
          -0.687061616,
          0.229186354,
          0.652812134
        ]
      },
      {
        "name": "lowerarm_r",
        "parent": "upperarm_r",
        "restLocalPosition": [
          0.012218,
          0.241785,
          0.01272
        ],
        "restWorldPosition": [
          -0.464199,
          1.335684,
          -0.018236
        ],
        "restWorldQuaternion": [
          0.005268738,
          0.006906686,
          0.738163114,
          0.674566346
        ],
        "restLocalQuaternion": [
          0.017182318,
          0.000020639,
          -5.36e-7,
          0.999852373
        ]
      },
      {
        "name": "hand_r",
        "parent": "lowerarm_r",
        "restLocalPosition": [
          0.001011,
          0.257463,
          0.004936
        ],
        "restWorldPosition": [
          -0.72059,
          1.31358,
          -0.008847
        ],
        "restWorldQuaternion": [
          -0.000545997,
          0.000543618,
          0.738195061,
          0.674586879
        ],
        "restLocalQuaternion": [
          -0.008619736,
          -6.2e-8,
          -2.41e-7,
          0.999962849
        ]
      },
      {
        "name": "index_01_r",
        "parent": "hand_r",
        "restLocalPosition": [
          -0.00204,
          0.12747,
          0.047758
        ],
        "restWorldPosition": [
          -0.847364,
          1.300167,
          0.038923
        ],
        "restWorldQuaternion": [
          0.521598768,
          -0.476622051,
          0.522367084,
          0.477387447
        ],
        "restLocalQuaternion": [
          3.25e-7,
          -0.707109344,
          2.41e-7,
          0.707104218
        ]
      },
      {
        "name": "index_02_r",
        "parent": "index_01_r",
        "restLocalPosition": [
          0.009715,
          0.021581,
          0.00786
        ],
        "restWorldPosition": [
          -0.868152,
          1.290414,
          0.048651
        ],
        "restWorldQuaternion": [
          0.521598672,
          -0.476621962,
          0.522367181,
          0.477387537
        ],
        "restLocalQuaternion": [
          0,
          1.86e-7,
          -1e-9,
          1
        ]
      },
      {
        "name": "index_03_r",
        "parent": "index_02_r",
        "restLocalPosition": [
          0.004119,
          0.016615,
          0.024528
        ],
        "restWorldPosition": [
          -0.882495,
          1.264498,
          0.052809
        ],
        "restWorldQuaternion": [
          0.52159868,
          -0.476621953,
          0.522367173,
          0.477387545
        ],
        "restLocalQuaternion": [
          0,
          0,
          -1.7e-8,
          1
        ]
      },
      {
        "name": "middle_01_r",
        "parent": "hand_r",
        "restLocalPosition": [
          -0.006063,
          0.134645,
          0.019316
        ],
        "restWorldPosition": [
          -0.854147,
          1.295471,
          0.010487
        ],
        "restWorldQuaternion": [
          0.510195101,
          -0.488809619,
          0.533497715,
          0.464915372
        ],
        "restLocalQuaternion": [
          -0.016702102,
          -0.706912084,
          0.016702789,
          0.706906898
        ]
      },
      {
        "name": "middle_02_r",
        "parent": "middle_01_r",
        "restLocalPosition": [
          0.006743,
          0.023216,
          0.012649
        ],
        "restWorldPosition": [
          -0.876424,
          1.280769,
          0.016147
        ],
        "restWorldQuaternion": [
          0.510934284,
          -0.488036738,
          0.532793489,
          0.465722447
        ],
        "restLocalQuaternion": [
          -1e-8,
          1.84e-7,
          -0.001513618,
          0.999998854
        ]
      },
      {
        "name": "middle_03_r",
        "parent": "middle_02_r",
        "restLocalPosition": [
          0.006354,
          0.021663,
          0.012171
        ],
        "restWorldPosition": [
          -0.897165,
          1.266686,
          0.021556
        ],
        "restWorldQuaternion": [
          0.510382652,
          -0.488613599,
          0.533319255,
          0.465120277
        ],
        "restLocalQuaternion": [
          8e-9,
          0,
          0.001129648,
          0.999999362
        ]
      },
      {
        "name": "pinky_01_r",
        "parent": "hand_r",
        "restLocalPosition": [
          -0.019206,
          0.10714,
          -0.034147
        ],
        "restWorldPosition": [
          -0.825568,
          1.284771,
          -0.042957
        ],
        "restWorldQuaternion": [
          0.505326772,
          -0.493840882,
          0.538078083,
          0.459606369
        ],
        "restLocalQuaternion": [
          -0.023705656,
          -0.706711946,
          0.023706332,
          0.706706641
        ]
      },
      {
        "name": "pinky_02_r",
        "parent": "pinky_01_r",
        "restLocalPosition": [
          -0.003217,
          0.024991,
          0.008783
        ],
        "restWorldPosition": [
          -0.849397,
          1.273794,
          -0.047826
        ],
        "restWorldQuaternion": [
          0.504914508,
          -0.494262198,
          0.538461421,
          0.459157399
        ],
        "restLocalQuaternion": [
          5e-9,
          1.83e-7,
          0.000834261,
          0.999999652
        ]
      },
      {
        "name": "pinky_03_r",
        "parent": "pinky_02_r",
        "restLocalPosition": [
          0.001478,
          0.020492,
          0.017966
        ],
        "restWorldPosition": [
          -0.868244,
          1.254055,
          -0.047729
        ],
        "restWorldQuaternion": [
          0.505215666,
          -0.493954362,
          0.538181462,
          0.459485509
        ],
        "restLocalQuaternion": [
          -4e-9,
          0,
          -0.000609502,
          0.999999814
        ]
      },
      {
        "name": "ring_01_r",
        "parent": "hand_r",
        "restLocalPosition": [
          -0.015727,
          0.139632,
          -0.010842
        ],
        "restWorldPosition": [
          -0.858243,
          1.285352,
          -0.019655
        ],
        "restWorldQuaternion": [
          0.51303076,
          -0.485832526,
          0.530783371,
          0.468011975
        ],
        "restLocalQuaternion": [
          -0.012588363,
          -0.706997247,
          0.012588999,
          0.70699218
        ]
      },
      {
        "name": "ring_02_r",
        "parent": "ring_01_r",
        "restLocalPosition": [
          0.003345,
          0.026352,
          0.008811
        ],
        "restWorldPosition": [
          -0.883799,
          1.274203,
          -0.017235
        ],
        "restWorldQuaternion": [
          0.513036615,
          -0.485826153,
          0.530777731,
          0.468018569
        ],
        "restLocalQuaternion": [
          0,
          1.84e-7,
          -0.000012254,
          1
        ]
      },
      {
        "name": "ring_03_r",
        "parent": "ring_02_r",
        "restLocalPosition": [
          0.004011,
          0.019877,
          0.019299
        ],
        "restWorldPosition": [
          -0.901991,
          1.253189,
          -0.013903
        ],
        "restWorldQuaternion": [
          0.512517889,
          -0.486373348,
          0.531276867,
          0.467451892
        ],
        "restLocalQuaternion": [
          7e-9,
          0,
          0.001067127,
          0.999999431
        ]
      },
      {
        "name": "thumb_01_r",
        "parent": "hand_r",
        "restLocalPosition": [
          -0.024673,
          0.056413,
          0.05975
        ],
        "restWorldPosition": [
          -0.774562,
          1.284029,
          0.050945
        ],
        "restWorldQuaternion": [
          0.864942354,
          -0.455463628,
          -0.097300936,
          0.1869763
        ],
        "restLocalQuaternion": [
          0.247412745,
          -0.945794479,
          -0.2034414,
          0.053584834
        ]
      },
      {
        "name": "thumb_02_r",
        "parent": "thumb_01_r",
        "restLocalPosition": [
          -0.00297,
          0.032447,
          -0.008642
        ],
        "restWorldPosition": [
          -0.797701,
          1.27179,
          0.072183
        ],
        "restWorldQuaternion": [
          0.864946151,
          -0.455394873,
          -0.09730768,
          0.187122635
        ],
        "restLocalQuaternion": [
          -0.000135623,
          0.000074042,
          -0.000048221,
          0.999999987
        ]
      },
      {
        "name": "thumb_03_r",
        "parent": "thumb_02_r",
        "restLocalPosition": [
          0.000276,
          0.03114,
          0.000609
        ],
        "restWorldPosition": [
          -0.821149,
          1.255376,
          0.084469
        ],
        "restWorldQuaternion": [
          0.864740643,
          -0.455897337,
          -0.097164509,
          0.186923237
        ],
        "restLocalQuaternion": [
          0.000248106,
          -0.00008099,
          0.000535578,
          0.999999823
        ]
      },
      {
        "name": "thigh_l",
        "parent": "pelvis",
        "restLocalPosition": [
          0.126674,
          0.036296,
          0.059873
        ],
        "restWorldPosition": [
          0.126674,
          0.894561,
          0.019253
        ],
        "restWorldQuaternion": [
          0.999993892,
          4e-9,
          1.5e-8,
          -0.003495273
        ],
        "restLocalQuaternion": [
          0.992484238,
          4e-9,
          2.9e-8,
          0.122372534
        ]
      },
      {
        "name": "calf_l",
        "parent": "thigh_l",
        "restLocalPosition": [
          0.045636,
          0.391544,
          0.038758
        ],
        "restWorldPosition": [
          0.17231,
          0.503298,
          -0.022241
        ],
        "restWorldQuaternion": [
          0.999196372,
          0.000005256,
          -0.000131156,
          -0.040082334
        ],
        "restLocalQuaternion": [
          0.036589625,
          -0.000131188,
          -0.000004794,
          0.999330367
        ]
      },
      {
        "name": "foot_l",
        "parent": "calf_l",
        "restLocalPosition": [
          0.059429,
          0.392466,
          0.012968
        ],
        "restWorldPosition": [
          0.231736,
          0.113133,
          -0.066619
        ],
        "restWorldQuaternion": [
          0.869100658,
          -0.000256172,
          -0.000450109,
          0.494634995
        ],
        "restLocalQuaternion": [
          -0.52907304,
          -0.000328091,
          0.00034345,
          0.848576156
        ]
      },
      {
        "name": "ball_l",
        "parent": "foot_l",
        "restLocalPosition": [
          0.001294,
          0.147717,
          0.016346
        ],
        "restWorldPosition": [
          0.233013,
          0.023643,
          0.052036
        ],
        "restWorldQuaternion": [
          -1.15e-7,
          0.707106938,
          0.707106624,
          -5.3e-8
        ],
        "restLocalQuaternion": [
          0.000137144,
          -0.964306669,
          0.264787424,
          0.000499542
        ]
      },
      {
        "name": "ball_leaf_l",
        "parent": "ball_l",
        "restLocalPosition": [
          0,
          0.082302,
          0
        ],
        "restWorldPosition": [
          0.233013,
          0.023643,
          0.134339
        ],
        "restWorldQuaternion": [
          -9.2e-8,
          0.707106905,
          0.707106657,
          -3e-8
        ],
        "restLocalQuaternion": [
          -4.7e-8,
          -3.3e-8,
          0,
          1
        ]
      },
      {
        "name": "thigh_r",
        "parent": "pelvis",
        "restLocalPosition": [
          -0.126674,
          0.036296,
          0.059873
        ],
        "restWorldPosition": [
          -0.126674,
          0.894561,
          0.019253
        ],
        "restWorldQuaternion": [
          0.999993891,
          1.3e-8,
          5.4e-8,
          -0.003495281
        ],
        "restLocalQuaternion": [
          0.992484239,
          1.8e-8,
          6.7e-8,
          0.122372526
        ]
      },
      {
        "name": "calf_r",
        "parent": "thigh_r",
        "restLocalPosition": [
          -0.045636,
          0.391544,
          0.038758
        ],
        "restWorldPosition": [
          -0.17231,
          0.503298,
          -0.022241
        ],
        "restWorldQuaternion": [
          0.999196371,
          0.000005265,
          -0.000131156,
          -0.040082342
        ],
        "restLocalQuaternion": [
          0.036589625,
          -0.000131227,
          -0.000004792,
          0.999330367
        ]
      },
      {
        "name": "foot_r",
        "parent": "calf_r",
        "restLocalPosition": [
          -0.059429,
          0.392466,
          0.012968
        ],
        "restWorldPosition": [
          -0.231742,
          0.11313,
          -0.066588
        ],
        "restWorldQuaternion": [
          0.869100621,
          -0.000256172,
          -0.000450109,
          0.49463506
        ],
        "restLocalQuaternion": [
          -0.529073109,
          -0.000328096,
          0.000343458,
          0.848576113
        ]
      },
      {
        "name": "ball_r",
        "parent": "foot_r",
        "restLocalPosition": [
          -0.001294,
          0.147717,
          0.016346
        ],
        "restWorldPosition": [
          -0.233053,
          0.023643,
          0.052069
        ],
        "restWorldQuaternion": [
          -1.15e-7,
          0.707106991,
          0.707106571,
          -5.3e-8
        ],
        "restLocalQuaternion": [
          0.000137145,
          -0.964306669,
          0.264787424,
          0.000499542
        ]
      },
      {
        "name": "ball_leaf_r",
        "parent": "ball_r",
        "restLocalPosition": [
          0,
          0.082302,
          0
        ],
        "restWorldPosition": [
          -0.233053,
          0.023643,
          0.134371
        ],
        "restWorldQuaternion": [
          -9.2e-8,
          0.707106969,
          0.707106594,
          -3e-8
        ],
        "restLocalQuaternion": [
          -3.2e-8,
          -3.3e-8,
          0,
          1
        ]
      }
    ]
  },
  "slots": {
    "helmet": {
      "slot": "helmet",
      "sourceJointName": "head",
      "endJointName": "head_leaf",
      "centerJointNames": [
        "head",
        "head_leaf"
      ],
      "pivotCenter": [
        0,
        1.5312,
        0.00635
      ],
      "pivotWorldPosition": [
        0,
        1.5312,
        0.00635
      ],
      "pivotWorldQuaternion": [
        0,
        0,
        0,
        1
      ],
      "basis": {
        "xAxis": [
          1,
          0,
          0
        ],
        "yAxis": [
          0,
          1,
          0
        ],
        "zAxis": [
          0,
          0,
          1
        ],
        "quaternion": [
          0,
          0,
          0,
          1
        ]
      },
      "geometry": {
        "position": [
          -0.004792,
          0.169842,
          -0.073433
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "neck": {
      "slot": "neck",
      "sourceJointName": "neck_01",
      "endJointName": "head",
      "centerJointNames": [
        "neck_01",
        "head"
      ],
      "pivotCenter": [
        0,
        1.441425,
        -0.022564
      ],
      "pivotWorldPosition": [
        0,
        1.441425,
        -0.022564
      ],
      "pivotWorldQuaternion": [
        0,
        0,
        0,
        1
      ],
      "basis": {
        "xAxis": [
          1,
          0,
          0
        ],
        "yAxis": [
          0,
          1,
          0
        ],
        "zAxis": [
          0,
          0,
          1
        ],
        "quaternion": [
          0,
          0,
          0,
          1
        ]
      },
      "geometry": {
        "position": [
          -0.004792,
          0.087117,
          0.084856
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "chest": {
      "slot": "chest",
      "sourceJointName": "spine_03",
      "endJointName": "neck_01",
      "centerJointNames": [
        "spine_03",
        "neck_01"
      ],
      "pivotCenter": [
        0,
        1.303707,
        -0.031607
      ],
      "pivotWorldPosition": [
        0,
        1.303707,
        -0.031607
      ],
      "pivotWorldQuaternion": [
        0,
        0,
        0,
        1
      ],
      "basis": {
        "xAxis": [
          1,
          0,
          0
        ],
        "yAxis": [
          0,
          1,
          0
        ],
        "zAxis": [
          0,
          0,
          1
        ],
        "quaternion": [
          0,
          0,
          0,
          1
        ]
      },
      "geometry": {
        "position": [
          -0.004792,
          0.004418,
          0.093899
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "shoulderLeft": {
      "slot": "shoulderLeft",
      "sourceJointName": "clavicle_l",
      "endJointName": "upperarm_l",
      "centerJointNames": [
        "clavicle_l",
        "upperarm_l"
      ],
      "pivotCenter": [
        0.120022,
        1.352421,
        0.015988
      ],
      "pivotWorldPosition": [
        0.120022,
        1.352421,
        0.015988
      ],
      "pivotWorldQuaternion": [
        -0.134160764,
        0.143919919,
        -0.717174021,
        0.668542721
      ],
      "basis": {
        "xAxis": [
          -0.070103,
          -0.99754,
          0
        ],
        "yAxis": [
          0.920306,
          -0.064675,
          -0.385816
        ],
        "zAxis": [
          0.384866,
          -0.027047,
          0.922576
        ],
        "quaternion": [
          -0.134160764,
          0.143919919,
          -0.717174021,
          0.668542721
        ]
      },
      "geometry": {
        "position": [
          0,
          0,
          0
        ],
        "rotation": [
          0.396092,
          0,
          1.640957
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "shoulderRight": {
      "slot": "shoulderRight",
      "sourceJointName": "clavicle_r",
      "endJointName": "upperarm_r",
      "centerJointNames": [
        "clavicle_r",
        "upperarm_r"
      ],
      "pivotCenter": [
        -0.120022,
        1.352421,
        0.015988
      ],
      "pivotWorldPosition": [
        -0.120022,
        1.352421,
        0.015988
      ],
      "pivotWorldQuaternion": [
        -0.134160709,
        -0.143919852,
        0.717174015,
        0.668542753
      ],
      "basis": {
        "xAxis": [
          -0.070103,
          0.99754,
          0
        ],
        "yAxis": [
          -0.920306,
          -0.064675,
          -0.385815
        ],
        "zAxis": [
          -0.384866,
          -0.027047,
          0.922576
        ],
        "quaternion": [
          -0.134160709,
          -0.143919852,
          0.717174015,
          0.668542753
        ]
      },
      "geometry": {
        "position": [
          0,
          0,
          0
        ],
        "rotation": [
          0.396092,
          0,
          -1.640957
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "upperArmLeft": {
      "slot": "upperArmLeft",
      "sourceJointName": "upperarm_l",
      "endJointName": "lowerarm_l",
      "centerJointNames": [
        "upperarm_l",
        "lowerarm_l"
      ],
      "pivotCenter": [
        0.343156,
        1.340465,
        -0.022523
      ],
      "pivotWorldPosition": [
        0.343156,
        1.340465,
        -0.022523
      ],
      "pivotWorldQuaternion": [
        0.012257968,
        -0.012751747,
        -0.720814244,
        0.692902562
      ],
      "basis": {
        "xAxis": [
          -0.039472,
          -0.999221,
          0
        ],
        "yAxis": [
          0.998595,
          -0.039447,
          0.03537
        ],
        "zAxis": [
          -0.035343,
          0.001396,
          0.999374
        ],
        "quaternion": [
          0.012257968,
          -0.012751747,
          -0.720814244,
          0.692902562
        ]
      },
      "geometry": {
        "position": [
          0,
          0,
          0
        ],
        "rotation": [
          -0.035378,
          0,
          1.610278
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "upperArmRight": {
      "slot": "upperArmRight",
      "sourceJointName": "upperarm_r",
      "endJointName": "lowerarm_r",
      "centerJointNames": [
        "upperarm_r",
        "lowerarm_r"
      ],
      "pivotCenter": [
        -0.343156,
        1.340465,
        -0.022523
      ],
      "pivotWorldPosition": [
        -0.343156,
        1.340465,
        -0.022523
      ],
      "pivotWorldQuaternion": [
        0.012257945,
        0.012751722,
        0.720814238,
        0.692902569
      ],
      "basis": {
        "xAxis": [
          -0.039472,
          0.999221,
          0
        ],
        "yAxis": [
          -0.998595,
          -0.039447,
          0.03537
        ],
        "zAxis": [
          0.035343,
          0.001396,
          0.999374
        ],
        "quaternion": [
          0.012257945,
          0.012751722,
          0.720814238,
          0.692902569
        ]
      },
      "geometry": {
        "position": [
          0,
          0,
          0
        ],
        "rotation": [
          -0.035378,
          0,
          -1.610278
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "forearmLeft": {
      "slot": "forearmLeft",
      "sourceJointName": "lowerarm_l",
      "endJointName": "hand_l",
      "centerJointNames": [
        "lowerarm_l",
        "hand_l"
      ],
      "pivotCenter": [
        0.592395,
        1.324632,
        -0.013542
      ],
      "pivotWorldPosition": [
        0.592395,
        1.324632,
        -0.013542
      ],
      "pivotWorldQuaternion": [
        0.012326566,
        -0.013435012,
        -0.736727281,
        0.675944132
      ],
      "basis": {
        "xAxis": [
          -0.085895,
          -0.996304,
          0
        ],
        "yAxis": [
          0.995642,
          -0.085838,
          0.03646
        ],
        "zAxis": [
          -0.036325,
          0.003132,
          0.999335
        ],
        "quaternion": [
          0.012326566,
          -0.013435012,
          -0.736727281,
          0.675944132
        ]
      },
      "geometry": {
        "position": [
          0,
          0,
          0
        ],
        "rotation": [
          -0.036468,
          0,
          1.656797
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "forearmRight": {
      "slot": "forearmRight",
      "sourceJointName": "lowerarm_r",
      "endJointName": "hand_r",
      "centerJointNames": [
        "lowerarm_r",
        "hand_r"
      ],
      "pivotCenter": [
        -0.592395,
        1.324632,
        -0.013541
      ],
      "pivotWorldPosition": [
        -0.592395,
        1.324632,
        -0.013541
      ],
      "pivotWorldQuaternion": [
        0.012326622,
        0.013435076,
        0.736727346,
        0.675944059
      ],
      "basis": {
        "xAxis": [
          -0.085895,
          0.996304,
          0
        ],
        "yAxis": [
          -0.995642,
          -0.085838,
          0.03646
        ],
        "zAxis": [
          0.036325,
          0.003132,
          0.999335
        ],
        "quaternion": [
          0.012326622,
          0.013435076,
          0.736727346,
          0.675944059
        ]
      },
      "geometry": {
        "position": [
          0,
          0,
          0
        ],
        "rotation": [
          -0.036468,
          0,
          -1.656798
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "handLeft": {
      "slot": "handLeft",
      "sourceJointName": "hand_l",
      "endJointName": "index_01_l",
      "centerJointNames": [
        "hand_l",
        "index_01_l",
        "middle_01_l",
        "ring_01_l",
        "pinky_01_l",
        "thumb_01_l"
      ],
      "pivotCenter": [
        0.813412,
        1.293895,
        0.004816
      ],
      "pivotWorldPosition": [
        0.813412,
        1.293895,
        0.004816
      ],
      "pivotWorldQuaternion": [
        0.119262685,
        -0.132546723,
        -0.731463801,
        0.658155366
      ],
      "basis": {
        "xAxis": [
          -0.105216,
          -0.994449,
          0
        ],
        "yAxis": [
          0.931218,
          -0.098526,
          0.350893
        ],
        "zAxis": [
          -0.348945,
          0.03692,
          0.936416
        ],
        "quaternion": [
          0.119262685,
          -0.132546723,
          -0.731463801,
          0.658155366
        ]
      },
      "geometry": {
        "position": [
          0,
          0,
          0
        ],
        "rotation": [
          -0.358525,
          0,
          1.676207
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "handRight": {
      "slot": "handRight",
      "sourceJointName": "hand_r",
      "endJointName": "index_01_r",
      "centerJointNames": [
        "hand_r",
        "index_01_r",
        "middle_01_r",
        "ring_01_r",
        "pinky_01_r",
        "thumb_01_r"
      ],
      "pivotCenter": [
        -0.813412,
        1.293895,
        0.004816
      ],
      "pivotWorldPosition": [
        -0.813412,
        1.293895,
        0.004816
      ],
      "pivotWorldQuaternion": [
        0.119262733,
        0.132546733,
        0.731463689,
        0.65815548
      ],
      "basis": {
        "xAxis": [
          -0.105216,
          0.994449,
          0
        ],
        "yAxis": [
          -0.931218,
          -0.098525,
          0.350893
        ],
        "zAxis": [
          0.348945,
          0.036919,
          0.936416
        ],
        "quaternion": [
          0.119262733,
          0.132546733,
          0.731463689,
          0.65815548
        ]
      },
      "geometry": {
        "position": [
          0,
          0,
          0
        ],
        "rotation": [
          -0.358525,
          0,
          -1.676207
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "pelvis": {
      "slot": "pelvis",
      "sourceJointName": "pelvis",
      "endJointName": "spine_01",
      "centerJointNames": [
        "pelvis",
        "spine_01"
      ],
      "pivotCenter": [
        0,
        0.922378,
        -0.035406
      ],
      "pivotWorldPosition": [
        0,
        0.922378,
        -0.035406
      ],
      "pivotWorldQuaternion": [
        0,
        0,
        0,
        1
      ],
      "basis": {
        "xAxis": [
          1,
          0,
          0
        ],
        "yAxis": [
          0,
          1,
          0
        ],
        "zAxis": [
          0,
          0,
          1
        ],
        "quaternion": [
          0,
          0,
          0,
          1
        ]
      },
      "geometry": {
        "position": [
          -0.004792,
          0.112622,
          -0.012511
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "thighLeft": {
      "slot": "thighLeft",
      "sourceJointName": "thigh_l",
      "endJointName": "calf_l",
      "centerJointNames": [
        "thigh_l",
        "calf_l"
      ],
      "pivotCenter": [
        0.149492,
        0.698929,
        -0.001494
      ],
      "pivotWorldPosition": [
        0.149492,
        0.698929,
        -0.001494
      ],
      "pivotWorldQuaternion": [
        0.003043416,
        -0.052362362,
        0.996941004,
        -0.057944417
      ],
      "basis": {
        "xAxis": [
          -0.993266,
          -0.115853,
          0
        ],
        "yAxis": [
          0.115216,
          -0.987801,
          -0.104757
        ],
        "zAxis": [
          0.012136,
          -0.104052,
          0.994498
        ],
        "quaternion": [
          0.003043416,
          -0.052362362,
          0.996941004,
          -0.057944417
        ]
      },
      "geometry": {
        "position": [
          0.01237,
          -0.020713,
          -0.05368
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "thighRight": {
      "slot": "thighRight",
      "sourceJointName": "thigh_r",
      "endJointName": "calf_r",
      "centerJointNames": [
        "thigh_r",
        "calf_r"
      ],
      "pivotCenter": [
        -0.149492,
        0.698929,
        -0.001494
      ],
      "pivotWorldPosition": [
        -0.149492,
        0.698929,
        -0.001494
      ],
      "pivotWorldQuaternion": [
        -0.003043416,
        -0.052362378,
        0.996941004,
        0.057944394
      ],
      "basis": {
        "xAxis": [
          -0.993266,
          0.115853,
          0
        ],
        "yAxis": [
          -0.115216,
          -0.987801,
          -0.104757
        ],
        "zAxis": [
          -0.012136,
          -0.104052,
          0.994498
        ],
        "quaternion": [
          -0.003043416,
          -0.052362378,
          0.996941004,
          0.057944394
        ]
      },
      "geometry": {
        "position": [
          -0.002852,
          -0.019609,
          -0.053563
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "shinLeft": {
      "slot": "shinLeft",
      "sourceJointName": "calf_l",
      "endJointName": "foot_l",
      "centerJointNames": [
        "calf_l",
        "foot_l"
      ],
      "pivotCenter": [
        0.202023,
        0.308215,
        -0.04443
      ],
      "pivotWorldPosition": [
        0.202023,
        0.308215,
        -0.04443
      ],
      "pivotWorldQuaternion": [
        0.004224997,
        -0.055799461,
        0.995583225,
        -0.075383101
      ],
      "basis": {
        "xAxis": [
          -0.988599,
          -0.150572,
          0
        ],
        "yAxis": [
          0.149629,
          -0.982408,
          -0.111743
        ],
        "zAxis": [
          0.016825,
          -0.110469,
          0.993737
        ],
        "quaternion": [
          0.004224997,
          -0.055799461,
          0.995583225,
          -0.075383101
        ]
      },
      "geometry": {
        "position": [
          -0.003237,
          -0.083724,
          -0.061142
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "shinRight": {
      "slot": "shinRight",
      "sourceJointName": "calf_r",
      "endJointName": "foot_r",
      "centerJointNames": [
        "calf_r",
        "foot_r"
      ],
      "pivotCenter": [
        -0.202026,
        0.308214,
        -0.044414
      ],
      "pivotWorldPosition": [
        -0.202026,
        0.308214,
        -0.044414
      ],
      "pivotWorldQuaternion": [
        -0.004222476,
        -0.055760205,
        0.995584815,
        0.075391284
      ],
      "basis": {
        "xAxis": [
          -0.988597,
          0.150588,
          0
        ],
        "yAxis": [
          -0.149646,
          -0.982414,
          -0.111665
        ],
        "zAxis": [
          -0.016815,
          -0.110391,
          0.993746
        ],
        "quaternion": [
          -0.004222476,
          -0.055760205,
          0.995584815,
          0.075391284
        ]
      },
      "geometry": {
        "position": [
          0.007972,
          -0.083012,
          -0.06107
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "footLeft": {
      "slot": "footLeft",
      "sourceJointName": "foot_l",
      "endJointName": "ball_l",
      "centerJointNames": [
        "foot_l",
        "ball_l"
      ],
      "pivotCenter": [
        0.232374,
        0.068388,
        -0.007292
      ],
      "pivotWorldPosition": [
        0.232374,
        0.068388,
        -0.007292
      ],
      "pivotWorldQuaternion": [
        0,
        0.00538197,
        0,
        0.999985517
      ],
      "basis": {
        "xAxis": [
          0.999942,
          0,
          -0.010764
        ],
        "yAxis": [
          0,
          1,
          0
        ],
        "zAxis": [
          0.010764,
          0,
          0.999942
        ],
        "quaternion": [
          0,
          0.00538197,
          0,
          0.999985517
        ]
      },
      "geometry": {
        "position": [
          0.0078,
          0.032237,
          -0.05492
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "footRight": {
      "slot": "footRight",
      "sourceJointName": "foot_r",
      "endJointName": "ball_r",
      "centerJointNames": [
        "foot_r",
        "ball_r"
      ],
      "pivotCenter": [
        -0.232398,
        0.068386,
        -0.00726
      ],
      "pivotWorldPosition": [
        -0.232398,
        0.068386,
        -0.00726
      ],
      "pivotWorldQuaternion": [
        0,
        -0.005524576,
        0,
        0.999984739
      ],
      "basis": {
        "xAxis": [
          0.999939,
          0,
          0.011049
        ],
        "yAxis": [
          0,
          1,
          0
        ],
        "zAxis": [
          -0.011049,
          0,
          0.999939
        ],
        "quaternion": [
          0,
          -0.005524576,
          0,
          0.999984739
        ]
      },
      "geometry": {
        "position": [
          -0.017376,
          0.032239,
          -0.054844
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    },
    "back": {
      "slot": "back",
      "sourceJointName": "spine_03",
      "endJointName": null,
      "centerJointNames": [
        "spine_03"
      ],
      "pivotCenter": [
        0,
        1.222487,
        -0.012819
      ],
      "pivotWorldPosition": [
        0,
        1.222487,
        -0.012819
      ],
      "pivotWorldQuaternion": [
        0,
        0,
        0,
        1
      ],
      "basis": {
        "xAxis": [
          1,
          0,
          0
        ],
        "yAxis": [
          0,
          1,
          0
        ],
        "zAxis": [
          0,
          0,
          1
        ],
        "quaternion": [
          0,
          0,
          0,
          1
        ]
      },
      "geometry": {
        "position": [
          -0.004792,
          0.171888,
          -0.169264
        ],
        "rotation": [
          0,
          0,
          0
        ],
        "scale": [
          1,
          1,
          1
        ]
      }
    }
  }
} as const;
