import { readFileSync, writeFileSync } from 'node:fs';
const source = JSON.parse(readFileSync('output/blender-repair/blender-weapons.json', 'utf8'));
for (const id of ['hammer', 'sword']) {
  if (!source[id]?.meshes?.length) throw new Error(`Missing ${id}`);
  for (const mesh of source[id].meshes) {
    if (mesh.positions.length % 9 || mesh.normals.length !== mesh.positions.length ||
        !mesh.positions.every(Number.isFinite) || !mesh.normals.every(Number.isFinite)) throw new Error(`Invalid ${mesh.name}`);
  }
}
writeFileSync('src/components/v3/v3BlenderWeapons.generated.ts',
  `// Generated by Blender author-weapons.py; meters, grip at origin.\nimport type { V3BlenderWeaponSet } from './v3BlenderWeaponModels';\nexport const V3_BLENDER_WEAPONS: V3BlenderWeaponSet = JSON.parse(${JSON.stringify(JSON.stringify(source))});\n`);
console.log('Generated Blender hammer and katar geometry.');
