import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  V3_MIXAMO_DEFAULT_SOURCE_FILE_NAMES,
  buildV3MixamoClipSetArtifact,
  buildV3MixamoClipArtifactFromDirectory,
  buildV3MixamoGeneratedSource,
  type BuildV3MixamoClipSetOptions,
  type V3MixamoClipSetArtifact,
} from './v3MixamoImporter';

export interface V3MixamoClipGenerationOptions {
  inputDirectory: string;
  outputPath: string;
}

export function generateV3MixamoClipSourceFile(
  options: V3MixamoClipGenerationOptions
) {
  const artifact = buildV3MixamoClipArtifactFromDirectory(options.inputDirectory);
  writeFileSync(options.outputPath, buildV3MixamoGeneratedSource(artifact), 'utf8');
  return artifact;
}

export interface GenerateV3MixamoClipsOptions extends BuildV3MixamoClipSetOptions {
  outputPath: string;
  exportName?: string;
}

export function buildV3MixamoClipsGeneratedSource(
  artifact: V3MixamoClipSetArtifact,
  exportName = 'V3_MIXAMO_CLIP_SET'
): string {
  return [
    '/* eslint-disable */',
    '// Generated by src/tools/generateV3MixamoClips.ts. Do not edit by hand.',
    `export const ${exportName} = ${JSON.stringify(artifact, null, 2)} as const;`,
    '',
  ].join('\n');
}

export function generateV3MixamoClipsSourceFile(
  options: GenerateV3MixamoClipsOptions
): V3MixamoClipSetArtifact {
  const artifact = buildV3MixamoClipSetArtifact(options);
  writeFileSync(
    options.outputPath,
    buildV3MixamoClipsGeneratedSource(artifact, options.exportName),
    'utf8'
  );
  return artifact;
}

function parseArgs(argv: readonly string[]): V3MixamoClipGenerationOptions {
  const inputIndex = argv.indexOf('--input');
  const outputIndex = argv.indexOf('--out');
  const inputDirectory = inputIndex >= 0
    ? argv[inputIndex + 1]
    : 'reference/mixamo-v3';
  const outputPath = outputIndex >= 0
    ? argv[outputIndex + 1]
    : 'src/components/grifball/v3MixamoClips.generated.ts';
  if (!inputDirectory || !outputPath) {
    throw new Error('Usage: node --import tsx src/tools/generateV3MixamoClips.ts --input <mixamo directory> --out <generated ts path>');
  }
  for (const fileName of Object.values(V3_MIXAMO_DEFAULT_SOURCE_FILE_NAMES)) {
    readFileSync(resolve(inputDirectory, fileName));
  }
  return {
    inputDirectory: resolve(inputDirectory),
    outputPath: resolve(outputPath),
  };
}

if (process.argv[1]?.endsWith('generateV3MixamoClips.ts')) {
  const artifact = generateV3MixamoClipSourceFile(parseArgs(process.argv.slice(2)));
  // eslint-disable-next-line no-console
  console.log(`Generated ${artifact.metrics.clipCount} V3 Mixamo clips (${artifact.metrics.totalKeyframes} keyframes).`);
}
