import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import {
  buildV3ObjVoxelizationArtifact,
  type V3ObjVoxelizationArtifact,
  type V3ObjVoxelRole,
} from './v3ObjVoxelizer';
import {
  V3_OBJ_SURFACE_VOXEL_ARTIFACT_SCHEMA,
  buildV3ObjSurfaceVoxelizationArtifact,
  type V3ObjSurfaceVoxelizationArtifact,
} from './v3ObjSurfaceVoxelizer';

export interface V3AegisGenerationOptions {
  inputPath: string;
  outputPath: string;
  mode?: 'legacy' | 'surface';
  gridScale?: number;
  targetHeightVoxels?: number;
  surfaceThicknessVoxels?: 0 | 1 | 2;
  includeUnknownObjects?: boolean;
}

type GeneratedRun = readonly [
  roleIndex: number,
  y: number,
  z: number,
  xStart: number,
  xEnd: number,
  emissive?: 1,
];

const GENERATED_HEADER = `/* eslint-disable */\n// Generated by src/tools/generateV3AegisFromObj.ts.\n// Source OBJ stays private/local; this file contains sanitized voxel runs only.\n`;

export function generateV3AegisReferenceVoxelSourceFile(
  options: V3AegisGenerationOptions
): V3ObjVoxelizationArtifact | V3ObjSurfaceVoxelizationArtifact {
  const objText = readFileSync(options.inputPath, 'utf8');
  const artifact = options.mode === 'surface'
    ? buildV3ObjSurfaceVoxelizationArtifact({
      objText,
      mtlText: readReferencedMtlText(options.inputPath, objText),
      fileName: options.inputPath,
    }, {
      targetHeightVoxels: options.targetHeightVoxels,
      surfaceThicknessVoxels: options.surfaceThicknessVoxels,
      includeUnknownObjects: options.includeUnknownObjects,
    })
    : buildV3ObjVoxelizationArtifact({
      objText,
      fileName: options.inputPath,
      gridScale: options.gridScale,
    });
  writeFileSync(options.outputPath, buildV3AegisGeneratedSource(artifact), 'utf8');
  return artifact;
}

export function buildV3AegisGeneratedSource(
  artifact: V3ObjVoxelizationArtifact | V3ObjSurfaceVoxelizationArtifact
): string {
  if (artifact.schemaVersion === V3_OBJ_SURFACE_VOXEL_ARTIFACT_SCHEMA) {
    return buildV3AegisSurfaceGeneratedSource(artifact);
  }
  return buildV3AegisLegacyGeneratedSource(artifact);
}

function buildV3AegisLegacyGeneratedSource(artifact: V3ObjVoxelizationArtifact): string {
  const rolePalette = buildRolePalette(artifact);
  const compactSource = {
    schemaVersion: 'v3-aegis-reference-voxels/v1',
    version: 1,
    source: artifact.source,
    gridScale: artifact.gridScale,
    rolePalette,
    metrics: artifact.metrics,
    slots: Object.fromEntries(Object.entries(artifact.slots).map(([slot, slotArtifact]) => [
      slot,
      {
        slot: slotArtifact.slot,
        gridScale: slotArtifact.gridScale,
        dimensions: slotArtifact.dimensions,
        bounds: slotArtifact.bounds,
        roleHintIndexes: slotArtifact.roleHints.map((role) => rolePalette.indexOf(role)),
        voxelCount: slotArtifact.voxelCount,
        runCount: slotArtifact.runCount,
        runs: slotArtifact.runs.map((run): GeneratedRun => {
          const roleIndex = rolePalette.indexOf(run.role);
          return run.emissive === true
            ? [roleIndex, run.y, run.z, run.xStart, run.xEnd, 1]
            : [roleIndex, run.y, run.z, run.xStart, run.xEnd];
        }),
      },
    ])),
  };

  return `${GENERATED_HEADER}\nexport const V3_AEGIS_REFERENCE_VOXEL_SOURCE = ${JSON.stringify(compactSource)} as const;\n`;
}

function buildV3AegisSurfaceGeneratedSource(artifact: V3ObjSurfaceVoxelizationArtifact): string {
  const rolePalette = artifact.rolePalette;
  const compactSource = {
    schemaVersion: artifact.schemaVersion,
    version: artifact.version,
    source: artifact.source,
    options: artifact.options,
    coordinateSystem: artifact.coordinateSystem,
    rolePalette,
    metrics: artifact.metrics,
    excludedObjects: artifact.excludedObjects,
    slots: Object.fromEntries(Object.entries(artifact.slots).map(([slot, slotArtifact]) => [
      slot,
      {
        slot: slotArtifact.slot,
        bounds: slotArtifact.bounds,
        roleHintIndexes: slotArtifact.roleHints.map((role) => rolePalette.indexOf(role)),
        voxelCount: slotArtifact.voxelCount,
        runCount: slotArtifact.runCount,
        runs: slotArtifact.runs.map((run): GeneratedRun => {
          const roleIndex = rolePalette.indexOf(run.role);
          return run.emissive === true
            ? [roleIndex, run.y, run.z, run.xStart, run.xEnd, 1]
            : [roleIndex, run.y, run.z, run.xStart, run.xEnd];
        }),
      },
    ])),
  };

  return `${GENERATED_HEADER}\nexport const V3_AEGIS_OBJ_SURFACE_VOXEL_SOURCE = ${JSON.stringify(compactSource)} as const;\n`;
}

function buildRolePalette(artifact: V3ObjVoxelizationArtifact): V3ObjVoxelRole[] {
  return [...new Set(
    Object.values(artifact.slots).flatMap((slot) => slot.roleHints)
  )].sort() as V3ObjVoxelRole[];
}

function readReferencedMtlText(inputPath: string, objText: string): string | undefined {
  const directory = dirname(inputPath);
  const materialLibraries = [...objText.matchAll(/^mtllib\s+(.+)$/gm)]
    .map((match) => match[1]?.trim())
    .filter((value): value is string => Boolean(value));
  const sources: string[] = [];
  for (const library of materialLibraries) {
    const resolvedPath = resolve(directory, library);
    if (existsSync(resolvedPath)) {
      sources.push(readFileSync(resolvedPath, 'utf8'));
    }
  }
  return sources.length > 0 ? sources.join('\n') : undefined;
}

function parseArgs(argv: readonly string[]): V3AegisGenerationOptions | undefined {
  if (argv.length === 0) return undefined;
  const inputIndex = argv.indexOf('--input');
  const outputIndex = argv.indexOf('--out');
  const gridScaleIndex = argv.indexOf('--grid-scale');
  const modeIndex = argv.indexOf('--mode');
  const targetHeightVoxelsIndex = argv.indexOf('--target-height-voxels');
  const surfaceThicknessVoxelsIndex = argv.indexOf('--surface-thickness-voxels');
  const inputPath = inputIndex >= 0 ? argv[inputIndex + 1] : undefined;
  const outputPath = outputIndex >= 0 ? argv[outputIndex + 1] : undefined;
  if (!inputPath || !outputPath) return undefined;
  const mode = modeIndex >= 0 && argv[modeIndex + 1] === 'surface' ? 'surface' : 'legacy';
  return {
    inputPath,
    outputPath,
    mode,
    gridScale: gridScaleIndex >= 0 ? Number(argv[gridScaleIndex + 1]) : undefined,
    targetHeightVoxels: targetHeightVoxelsIndex >= 0 ? Number(argv[targetHeightVoxelsIndex + 1]) : undefined,
    surfaceThicknessVoxels: normalizeSurfaceThicknessArg(
      surfaceThicknessVoxelsIndex >= 0 ? argv[surfaceThicknessVoxelsIndex + 1] : undefined
    ),
    includeUnknownObjects: argv.includes('--include-unknown-objects'),
  };
}

function normalizeSurfaceThicknessArg(value: string | undefined): 0 | 1 | 2 | undefined {
  if (value === '0') return 0;
  if (value === '1') return 1;
  if (value === '2') return 2;
  return undefined;
}

if (process.argv[1]?.replace(/\\/g, '/').endsWith('/src/tools/generateV3AegisFromObj.ts')) {
  const options = parseArgs(process.argv.slice(2));
  if (!options) {
    throw new Error('Usage: node --import tsx src/tools/generateV3AegisFromObj.ts --input <obj path> --out <generated ts path> [--mode surface --target-height-voxels 192]');
  }
  const artifact = generateV3AegisReferenceVoxelSourceFile(options);
  console.log(`Generated V3 Aegis ${options.mode ?? 'legacy'} voxels: ${artifact.metrics.totalVoxelCount} voxels across ${artifact.metrics.slotCount} slots.`);
}
