import { readFileSync, writeFileSync } from 'node:fs';
import {
  buildV3ObjVoxelizationArtifact,
  type V3ObjVoxelizationArtifact,
  type V3ObjVoxelRole,
} from './v3ObjVoxelizer';

export interface V3AegisGenerationOptions {
  inputPath: string;
  outputPath: string;
  gridScale?: number;
}

type GeneratedRun = readonly [
  roleIndex: number,
  y: number,
  z: number,
  xStart: number,
  xEnd: number,
  emissive?: 1,
];

const GENERATED_HEADER = `/* eslint-disable */\n// Generated by src/tools/generateV3AegisFromObj.ts.\n// Source OBJ stays private/local; this file contains sanitized voxel runs only.\n`;

export function generateV3AegisReferenceVoxelSourceFile(
  options: V3AegisGenerationOptions
): V3ObjVoxelizationArtifact {
  const objText = readFileSync(options.inputPath, 'utf8');
  const artifact = buildV3ObjVoxelizationArtifact({
    objText,
    fileName: options.inputPath,
    gridScale: options.gridScale,
  });
  writeFileSync(options.outputPath, buildV3AegisGeneratedSource(artifact), 'utf8');
  return artifact;
}

export function buildV3AegisGeneratedSource(artifact: V3ObjVoxelizationArtifact): string {
  const rolePalette = buildRolePalette(artifact);
  const compactSource = {
    schemaVersion: 'v3-aegis-reference-voxels/v1',
    version: 1,
    source: artifact.source,
    gridScale: artifact.gridScale,
    rolePalette,
    metrics: artifact.metrics,
    slots: Object.fromEntries(Object.entries(artifact.slots).map(([slot, slotArtifact]) => [
      slot,
      {
        slot: slotArtifact.slot,
        gridScale: slotArtifact.gridScale,
        dimensions: slotArtifact.dimensions,
        bounds: slotArtifact.bounds,
        roleHintIndexes: slotArtifact.roleHints.map((role) => rolePalette.indexOf(role)),
        voxelCount: slotArtifact.voxelCount,
        runCount: slotArtifact.runCount,
        runs: slotArtifact.runs.map((run): GeneratedRun => {
          const roleIndex = rolePalette.indexOf(run.role);
          return run.emissive === true
            ? [roleIndex, run.y, run.z, run.xStart, run.xEnd, 1]
            : [roleIndex, run.y, run.z, run.xStart, run.xEnd];
        }),
      },
    ])),
  };

  return `${GENERATED_HEADER}\nexport const V3_AEGIS_REFERENCE_VOXEL_SOURCE = ${JSON.stringify(compactSource)} as const;\n`;
}

function buildRolePalette(artifact: V3ObjVoxelizationArtifact): V3ObjVoxelRole[] {
  return [...new Set(
    Object.values(artifact.slots).flatMap((slot) => slot.roleHints)
  )].sort() as V3ObjVoxelRole[];
}

function parseArgs(argv: readonly string[]): V3AegisGenerationOptions | undefined {
  if (argv.length === 0) return undefined;
  const inputIndex = argv.indexOf('--input');
  const outputIndex = argv.indexOf('--out');
  const gridScaleIndex = argv.indexOf('--grid-scale');
  const inputPath = inputIndex >= 0 ? argv[inputIndex + 1] : undefined;
  const outputPath = outputIndex >= 0 ? argv[outputIndex + 1] : undefined;
  if (!inputPath || !outputPath) return undefined;
  return {
    inputPath,
    outputPath,
    gridScale: gridScaleIndex >= 0 ? Number(argv[gridScaleIndex + 1]) : undefined,
  };
}

if (process.argv[1]?.replace(/\\/g, '/').endsWith('/src/tools/generateV3AegisFromObj.ts')) {
  const options = parseArgs(process.argv.slice(2));
  if (!options) {
    throw new Error('Usage: node --import tsx src/tools/generateV3AegisFromObj.ts --input <obj path> --out <generated ts path> [--grid-scale 4]');
  }
  const artifact = generateV3AegisReferenceVoxelSourceFile(options);
  console.log(`Generated V3 Aegis reference voxels: ${artifact.metrics.totalVoxelCount} voxels across ${artifact.metrics.slotCount} slots.`);
}
