import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import {
  V3_MIXAMO_DEFAULT_SOURCE_FILE_NAMES,
  V3_MIXAMO_WEAPON_REFERENCE_SOURCE_FILE_NAMES,
  buildV3MixamoClipSetArtifact,
  buildV3MixamoClipArtifactFromDirectory,
  buildV3MixamoGeneratedSource,
  buildV3MixamoWeaponReferenceSetArtifact,
  type BuildV3MixamoClipSetOptions,
  type BuildV3MixamoWeaponReferenceSetOptions,
  type V3MixamoClipSetArtifact,
  type V3MixamoWeaponReferenceSetArtifact,
} from './v3MixamoImporter';

export interface V3MixamoClipGenerationOptions {
  inputDirectory: string;
  outputPath: string;
}

export function generateV3MixamoClipSourceFile(
  options: V3MixamoClipGenerationOptions
) {
  const artifact = buildV3MixamoClipArtifactFromDirectory(options.inputDirectory);
  writeFileSync(options.outputPath, buildV3MixamoGeneratedSource(artifact), 'utf8');
  return artifact;
}

export interface GenerateV3MixamoClipsOptions extends BuildV3MixamoClipSetOptions {
  outputPath: string;
  exportName?: string;
}

export interface GenerateV3MixamoWeaponReferencesOptions extends BuildV3MixamoWeaponReferenceSetOptions {
  outputPath: string;
  exportName?: string;
}

export function buildV3MixamoClipsGeneratedSource(
  artifact: V3MixamoClipSetArtifact,
  exportName = 'V3_MIXAMO_CLIP_SET'
): string {
  return [
    '/* eslint-disable */',
    '// Generated by src/tools/generateV3MixamoClips.ts. Do not edit by hand.',
    `export const ${exportName} = ${JSON.stringify(artifact, null, 2)} as const;`,
    '',
  ].join('\n');
}

export function generateV3MixamoClipsSourceFile(
  options: GenerateV3MixamoClipsOptions
): V3MixamoClipSetArtifact {
  const artifact = buildV3MixamoClipSetArtifact(options);
  writeFileSync(
    options.outputPath,
    buildV3MixamoClipsGeneratedSource(artifact, options.exportName),
    'utf8'
  );
  return artifact;
}

export function buildV3MixamoWeaponReferencesGeneratedSource(
  artifact: V3MixamoWeaponReferenceSetArtifact,
  exportName = 'V3_MIXAMO_WEAPON_REFERENCE_SET'
): string {
  const serialized = JSON.stringify(artifact);
  const forbiddenPatterns: Array<[RegExp, string]> = [
    [/[A-Za-z]:\\/, 'absolute Windows path'],
    [/\/Users\/|\\Users\\|\/home\/|\/tmp\//, 'private absolute path'],
    [/mixamorig/i, 'raw Mixamo bone names'],
    [/FBXHeaderExtension|Objects:|Geometry:|Vertices:/i, 'raw FBX payload'],
  ];
  const issues = forbiddenPatterns
    .filter(([pattern]) => pattern.test(serialized))
    .map(([, label]) => label);
  if (issues.length > 0) {
    throw new Error(`Refusing to generate unsanitized V3 Mixamo weapon references: ${issues.join(', ')}`);
  }
  return [
    '/* eslint-disable */',
    '// Generated by src/tools/generateV3MixamoClips.ts. Do not edit by hand.',
    '// Source Mixamo FBX files stay private/local; this file contains sanitized weapon reference data only.',
    `export const ${exportName} = ${JSON.stringify(artifact, null, 2)} as const;`,
    '',
  ].join('\n');
}

export function generateV3MixamoWeaponReferencesSourceFile(
  options: GenerateV3MixamoWeaponReferencesOptions
): V3MixamoWeaponReferenceSetArtifact {
  const artifact = buildV3MixamoWeaponReferenceSetArtifact(options);
  writeFileSync(
    options.outputPath,
    buildV3MixamoWeaponReferencesGeneratedSource(artifact, options.exportName),
    'utf8'
  );
  return artifact;
}

function parseArgs(argv: readonly string[]): V3MixamoClipGenerationOptions & { weaponReferences: boolean } {
  const inputIndex = argv.indexOf('--input');
  const outputIndex = argv.indexOf('--out');
  const weaponReferences = argv.includes('--weapon-references');
  const inputDirectory = inputIndex >= 0
    ? argv[inputIndex + 1]
    : 'reference/mixamo-v3';
  const outputPath = outputIndex >= 0
    ? argv[outputIndex + 1]
    : weaponReferences
      ? 'src/components/grifball/v3MixamoWeaponReferences.generated.ts'
      : 'src/components/grifball/v3MixamoClips.generated.ts';
  if (!inputDirectory || !outputPath) {
    throw new Error('Usage: node --import tsx src/tools/generateV3MixamoClips.ts [--weapon-references] --input <mixamo directory> --out <generated ts path>');
  }
  const sourceFileNames = weaponReferences
    ? Object.values(V3_MIXAMO_WEAPON_REFERENCE_SOURCE_FILE_NAMES)
    : Object.values(V3_MIXAMO_DEFAULT_SOURCE_FILE_NAMES);
  for (const fileName of sourceFileNames) {
    readFileSync(resolve(inputDirectory, fileName));
  }
  return {
    inputDirectory: resolve(inputDirectory),
    outputPath: resolve(outputPath),
    weaponReferences,
  };
}

if (process.argv[1]?.endsWith('generateV3MixamoClips.ts')) {
  const args = parseArgs(process.argv.slice(2));
  if (args.weaponReferences) {
    const artifact = generateV3MixamoWeaponReferencesSourceFile({
      sourceFiles: {
        hammer_2hand_idle: resolve(args.inputDirectory, V3_MIXAMO_WEAPON_REFERENCE_SOURCE_FILE_NAMES.hammer_2hand_idle),
        hammer_heavy_swing: resolve(args.inputDirectory, V3_MIXAMO_WEAPON_REFERENCE_SOURCE_FILE_NAMES.hammer_heavy_swing),
        hammer_melee_advance: resolve(args.inputDirectory, V3_MIXAMO_WEAPON_REFERENCE_SOURCE_FILE_NAMES.hammer_melee_advance),
        sword_outward_slash: resolve(args.inputDirectory, V3_MIXAMO_WEAPON_REFERENCE_SOURCE_FILE_NAMES.sword_outward_slash),
        hammer_smash_reference: resolve(args.inputDirectory, V3_MIXAMO_WEAPON_REFERENCE_SOURCE_FILE_NAMES.hammer_smash_reference),
      },
      outputPath: args.outputPath,
      fps: 30,
    });
    // eslint-disable-next-line no-console
    console.log(`Generated ${artifact.metrics.clipCount} V3 Mixamo weapon reference clips (${artifact.metrics.totalKeyframes} keyframes).`);
  } else {
    const artifact = generateV3MixamoClipSourceFile(args);
  // eslint-disable-next-line no-console
    console.log(`Generated ${artifact.metrics.clipCount} V3 Mixamo clips (${artifact.metrics.totalKeyframes} keyframes).`);
  }
}
